// Generated by scripts/build.js. Import this file directly into MusicFree.
var __getOwnPropNames = Object.getOwnPropertyNames;
var __commonJS = (cb, mod) => function __require() {
  return mod || (0, cb[__getOwnPropNames(cb)[0]])((mod = { exports: {} }).exports, mod), mod.exports;
};

// src/shared.js
var require_shared = __commonJS({
  "src/shared.js"(exports2, module2) {
    var axios2 = require("axios");
    var PAGE_SIZE2 = 30;
    var UA2 = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36";
    function text2(value, fallback) {
      if (value === void 0 || value === null || value === "") return fallback || "";
      return String(value);
    }
    function stripHtml2(value) {
      return text2(value).replace(/<[^>]*>/g, "").replace(/&amp;/g, "&").replace(/&lt;/g, "<").replace(/&gt;/g, ">").replace(/&quot;/g, '"').replace(/&#39;/g, "'").trim();
    }
    function toHttps2(value, size) {
      return text2(value).replace(/^http:\/\//i, "https://").replace(/\{size\}/g, text2(size, "400"));
    }
    function parseJsonp(value) {
      const raw = text2(value).trim();
      const start = raw.indexOf("(");
      const end = raw.lastIndexOf(")");
      return JSON.parse(start >= 0 && end > start ? raw.slice(start + 1, end) : raw);
    }
    function parseDuration2(value) {
      if (typeof value === "number") {
        return value > 1e5 ? Math.floor(value / 1e3) : Math.floor(value);
      }
      const raw = text2(value);
      if (/^\d+:\d{1,2}$/.test(raw)) {
        const parts = raw.split(":").map(Number);
        return parts[0] * 60 + parts[1];
      }
      const parsed = Number(raw);
      return Number.isFinite(parsed) ? Math.floor(parsed) : void 0;
    }
    function artistNames(list, separator) {
      if (!Array.isArray(list)) return text2(list, "\u672A\u77E5\u6B4C\u624B");
      return list.map(function(artist) {
        return text2(artist && (artist.name || artist.title || artist.author_name));
      }).filter(Boolean).join(separator || "\u3001");
    }
    function formatLrcTime(seconds) {
      const value = Number(seconds) || 0;
      const minutes = Math.floor(value / 60);
      const rest = (value - minutes * 60).toFixed(2).padStart(5, "0");
      return "[" + String(minutes).padStart(2, "0") + ":" + rest + "]";
    }
    function decodeBase64(value) {
      if (!value) return "";
      try {
        return Buffer.from(value, "base64").toString("utf8");
      } catch (error) {
        return text2(value);
      }
    }
    function userVariables() {
      try {
        return env.getUserVariables() || {};
      } catch (error) {
        return {};
      }
    }
    function qualityLevel(quality) {
      return {
        low: "standard",
        standard: "standard",
        high: "exhigh",
        super: "lossless"
      }[quality] || "standard";
    }
    async function resolveMedia2(source, musicItem, quality) {
      const rid = text2(musicItem.sourceRid || musicItem.rid || musicItem.id);
      const response = await axios2.post(
        "https://musicserver.haitangw.cc/v1/music/resolve-url",
        { source, rid, level: qualityLevel(quality) },
        {
          headers: { "Content-Type": "application/json", Accept: "application/json" },
          timeout: 9e3
        }
      );
      const data = response.data && response.data.data;
      if (!data || !data.url) throw new Error("\u64AD\u653E\u5730\u5740\u89E3\u6790\u5931\u8D25");
      return { url: data.url, headers: data.playbackHeaders || data.headers || void 0 };
    }
    function normalizeComment(item) {
      const rawTime = Number(item.time);
      return {
        id: text2(item.id),
        nickName: text2(item.userName, "\u533F\u540D\u7528\u6237"),
        comment: text2(item.text),
        avatar: text2(item.avatar),
        like: Number(item.likedCount) || 0,
        createAt: Number.isFinite(rawTime) ? rawTime < 1e11 ? rawTime * 1e3 : rawTime : void 0,
        location: text2(item.location),
        replies: Array.isArray(item.reply) ? item.reply.map(function(reply) {
          const normalized = normalizeComment(reply);
          delete normalized.replies;
          return normalized;
        }) : []
      };
    }
    async function getComments2(source, musicItem, page) {
      const currentPage = Math.max(1, Number(page) || 1);
      const rid = text2(musicItem.sourceRid || musicItem.rid || musicItem.id);
      const response = await axios2.get(
        "https://music.haitangw.cc/pinglun/" + source + "pl.php",
        {
          params: { songmid: rid, type: "hot", page: currentPage, limit: 20 },
          headers: { "User-Agent": UA2 },
          timeout: 8e3
        }
      );
      const root = response.data || {};
      if (Number(root.code) !== 200) throw new Error(root.message || "\u8BC4\u8BBA\u52A0\u8F7D\u5931\u8D25");
      const data = root.data || {};
      const comments = Array.isArray(data.comments) ? data.comments : [];
      return {
        isEnd: currentPage >= Number(data.maxPage || 1) || comments.length < 20,
        data: comments.map(normalizeComment)
      };
    }
    function extractNumericId2(value) {
      const matches = text2(value).match(/\d+/g);
      if (!matches || !matches.length) throw new Error("\u65E0\u6CD5\u8BC6\u522B ID");
      return matches[matches.length - 1];
    }
    module2.exports = {
      axios: axios2,
      PAGE_SIZE: PAGE_SIZE2,
      UA: UA2,
      text: text2,
      stripHtml: stripHtml2,
      toHttps: toHttps2,
      parseJsonp,
      parseDuration: parseDuration2,
      artistNames,
      formatLrcTime,
      decodeBase64,
      userVariables,
      resolveMedia: resolveMedia2,
      getComments: getComments2,
      extractNumericId: extractNumericId2
    };
  }
});

// src/kugou.js
var cheerio = require("cheerio");
var {
  axios,
  PAGE_SIZE,
  UA,
  text,
  stripHtml,
  toHttps,
  parseDuration,
  resolveMedia,
  getComments,
  extractNumericId
} = require_shared();
function splitFilename(value) {
  const raw = stripHtml(value);
  const index = raw.indexOf(" - ");
  if (index < 0) return { artist: "\u672A\u77E5\u6B4C\u624B", title: raw };
  return { artist: raw.slice(0, index), title: raw.slice(index + 3) };
}
function mapMusic(item) {
  const rid = text(item.hash || item.FileHash || item.Hash || item.HASH);
  const names = splitFilename(item.filename || item.FileName || item.SongName || item.songname);
  const cover = toHttps(
    item.album_sizable_cover || item.Image || item.image || item.trans_param && item.trans_param.union_cover,
    "400"
  );
  return {
    id: rid,
    title: stripHtml(item.songname || item.SongName || names.title),
    artist: stripHtml(item.singername || item.SingerName || names.artist),
    album: stripHtml(item.album_name || item.AlbumName || item.remark),
    duration: parseDuration(item.duration || item.Duration || item.timelength),
    artwork: cover,
    sourceRid: rid
  };
}
async function getTopLists() {
  const response = await axios.get("http://mobilecdnbj.kugou.com/api/v3/rank/list", {
    params: {
      version: 9108,
      plat: 0,
      showtype: 2,
      parentid: 0,
      apiver: 6,
      area_code: 1,
      withsong: 0,
      with_res_tag: 0
    },
    headers: { "User-Agent": UA, Referer: "https://www.kugou.com/" },
    timeout: 9e3
  });
  const list = response.data && response.data.data && response.data.data.info || [];
  const groups = [
    { title: "\u70ED\u95E8\u699C\u5355", classify: [1, 2], data: [] },
    { title: "\u7279\u8272\u97F3\u4E50\u699C", classify: [3, 5], data: [] },
    { title: "\u5168\u7403\u699C", classify: [4], data: [] }
  ];
  list.forEach(function(item) {
    const group = groups.find(function(candidate) {
      return candidate.classify.indexOf(Number(item.classify)) >= 0;
    });
    if (!group) return;
    const coverImg = toHttps(
      item.img_cover || item.imgurl || item.banner7url || item.bannerurl,
      "400"
    );
    group.data.push({
      id: text(item.rankid),
      bangId: text(item.rankid),
      title: text(item.rankname),
      description: text(item.intro),
      coverImg,
      artwork: coverImg,
      updateTime: text(item.rank_id_publish_date || item.update_frequency)
    });
  });
  return groups;
}
async function search(query, page, type) {
  if (type !== "music") return { isEnd: true, data: [] };
  const currentPage = Math.max(1, Number(page) || 1);
  const response = await axios.get("https://songsearch.kugou.com/song_search_v2", {
    params: {
      keyword: query,
      page: currentPage,
      pagesize: PAGE_SIZE,
      platform: "WebFilter",
      filter: 2,
      iscorrection: 1,
      privilege_filter: 0,
      area_code: 1
    },
    headers: { "User-Agent": UA, Referer: "https://www.kugou.com/" },
    timeout: 8e3
  });
  const root = response.data || {};
  const list = root.data && (root.data.lists || root.data.list) || [];
  return { isEnd: list.length < PAGE_SIZE, data: list.map(mapMusic) };
}
async function getLyric(musicItem) {
  const rid = text(musicItem.sourceRid || musicItem.id);
  const response = await axios.get("https://m.kugou.com/app/i/krc.php", {
    params: { cmd: 100, hash: rid, timelength: 1 },
    headers: { "User-Agent": UA, Referer: "https://m.kugou.com/" },
    responseType: "text",
    timeout: 8e3
  });
  return { rawLrc: text(response.data) };
}
async function getMusicInfo(musicItem) {
  const rid = text(musicItem.sourceRid || musicItem.id);
  const timestamp = Math.floor(Date.now() / 1e3);
  const response = await axios.post(
    "https://gateway.kugou.com/goodsmstore/v1/get_res_privilege?appid=1005&clientver=20049&clienttime=" + timestamp + "&mid=123",
    {
      behavior: "play",
      clientver: "20049",
      resource: [{ id: 0, type: "audio", hash: rid }],
      area_code: "1",
      quality: "128",
      qualities: ["128", "320", "flac", "high", "dolby", "viper_atmos", "viper_tape", "viper_clear"]
    },
    {
      headers: { "User-Agent": "Android/10 KugouMusic/13.0.0", "Content-Type": "application/json" },
      timeout: 8e3
    }
  );
  const item = response.data && response.data.data && response.data.data[0];
  const info = item && item.info;
  if (!item || !info) return {};
  return {
    title: splitFilename(item.name).title,
    artist: text(item.singername),
    album: text(item.albumname),
    artwork: text(info.image).replace("{size}", "720"),
    duration: parseDuration(info.duration),
    sourceRid: rid
  };
}
async function getTopListDetail(topListItem, page) {
  const currentPage = Math.max(1, Number(page) || 1);
  const response = await axios.get("http://mobilecdnbj.kugou.com/api/v3/rank/song", {
    params: {
      version: 9108,
      ranktype: 1,
      plat: 0,
      pagesize: 100,
      area_code: 1,
      page: currentPage,
      rankid: topListItem.bangId || topListItem.id,
      with_res_tag: 0,
      show_portrait_mv: 1
    },
    headers: { "User-Agent": UA, Referer: "https://www.kugou.com/" },
    timeout: 9e3
  });
  const data = response.data && response.data.data || {};
  const list = data.info || [];
  return {
    isEnd: currentPage * 100 >= Number(data.total || 0) || list.length < 100,
    musicList: list.map(mapMusic)
  };
}
async function getRecommendSheetsByTag(tag, page) {
  const currentPage = Math.max(1, Number(page) || 1);
  const tagId = text(tag && tag.id, "5");
  const response = await axios.get(
    "https://www.kugou.com/yy/special/index/" + currentPage + "-" + encodeURIComponent(tagId) + "-" + (currentPage === 1 ? "0" : "1") + ".html",
    {
      headers: { "User-Agent": UA, Referer: "https://www.kugou.com/" },
      responseType: "text",
      timeout: 8e3
    }
  );
  const $ = cheerio.load(text(response.data));
  const list = [];
  $("#ulAlbums > li").each(function(_, element) {
    const share = $(element).find("a.pc_temp_bicon_share").first();
    const play = $(element).find("a.pc_temp_bicon_play").first();
    if (!share.attr("data-id")) return;
    list.push({
      id: text(share.attr("data-id")),
      title: text(share.attr("data-collection") || $(element).find(".top strong a").text()),
      artist: text(share.attr("data-creat")).replace(/^制作人：/, ""),
      artwork: toHttps(share.attr("data-img")),
      description: $(element).find(".detail .text").text().trim(),
      globalCollectionId: text(play.attr("data-egcid"))
    });
  });
  return {
    isEnd: $('a[title="\u4E0B\u4E00\u9875"]').length === 0,
    data: list
  };
}
async function getRecommendSheetTags() {
  const response = await axios.get("https://www.kugou.com/yy/html/special.html", {
    headers: { "User-Agent": UA, Referer: "https://www.kugou.com/" },
    responseType: "text",
    timeout: 8e3
  });
  const $ = cheerio.load(text(response.data));
  const tags = [];
  $('a[href*="/yy/special/index/1-"]').each(function(_, element) {
    const href = text($(element).attr("href"));
    const match = href.match(/\/index\/1-(\d+)-0\.html/);
    if (!match || tags.some(function(item) {
      return item.id === match[1];
    })) return;
    tags.push({ id: match[1], title: text($(element).attr("title") || $(element).text()) });
  });
  return { pinned: tags.slice(0, 1), data: [{ title: "\u6B4C\u5355\u5206\u7C7B", data: tags }] };
}
function parseEmbeddedSongs(html) {
  const match = text(html).match(/var data=(\[[\s\S]*?\])\s*,\s*specialData\s*=/);
  if (!match) throw new Error("\u9177\u72D7\u6B4C\u5355\u9875\u9762\u672A\u627E\u5230\u6B4C\u66F2\u6570\u636E");
  return JSON.parse(match[1]);
}
async function getMusicSheetInfo(sheetItem, page) {
  const currentPage = Math.max(1, Number(page) || 1);
  if (currentPage > 1) return { isEnd: true, musicList: [] };
  const base = "https://m.kugou.com/plist/list/" + encodeURIComponent(sheetItem.id) + "/";
  const response = await axios.get(base + "?json=true&page=2", {
    headers: { "User-Agent": UA, Referer: "https://m.kugou.com/" },
    responseType: "text",
    timeout: 9e3
  });
  const root = response.data || {};
  const listRoot = typeof root === "object" && root.list && root.list.list;
  const info = typeof root === "object" && root.info && root.info.list;
  const allSongs = listRoot ? listRoot.info || [] : parseEmbeddedSongs(root);
  return {
    isEnd: true,
    musicList: allSongs.map(mapMusic),
    sheetItem: {
      title: text(info && info.specialname || sheetItem.title),
      artist: text(info && info.nickname || sheetItem.artist),
      artwork: toHttps(info && info.imgurl || sheetItem.artwork, "400"),
      description: text(info && info.intro || sheetItem.description),
      worksNum: Number(info && info.songcount) || allSongs.length,
      playCount: Number(info && info.playcount) || sheetItem.playCount || void 0
    }
  };
}
async function importMusicSheet(urlLike) {
  const id = extractNumericId(urlLike);
  return (await getMusicSheetInfo({ id, title: "\u5BFC\u5165\u6B4C\u5355" }, 1)).musicList;
}
module.exports = {
  platform: "\u9177\u72D7\u97F3\u4E50",
  version: "1.3.0",
  srcUrl: "https://droidzf.github.io/musicfree/kugou.js",
  author: "zero",
  description: "\u72EC\u7ACB\u9177\u72D7\u97F3\u4E50\u63D2\u4EF6\uFF1A\u641C\u7D22\u3001\u64AD\u653E\u3001\u6B4C\u8BCD\u3001\u5B98\u65B9\u52A8\u6001\u699C\u5355\u3001\u63A8\u8350\u6B4C\u5355\u3001\u6B4C\u5355\u8BE6\u60C5\u548C\u8BC4\u8BBA\u3002",
  cacheControl: "no-store",
  supportedSearchType: ["music"],
  hints: { importMusicSheet: ["\u652F\u6301\u9177\u72D7\u6B4C\u5355\u94FE\u63A5\u6216\u7EAF\u6570\u5B57\u6B4C\u5355 ID\u3002"] },
  search,
  getMediaSource: function(musicItem, quality) {
    return resolveMedia("kg", musicItem, quality);
  },
  getLyric,
  getMusicInfo,
  getTopLists,
  getTopListDetail,
  getRecommendSheetTags,
  getRecommendSheetsByTag,
  getMusicSheetInfo,
  importMusicSheet,
  getMusicComments: function(musicItem, page) {
    return getComments("kg", musicItem, page);
  }
};
