// Generated by scripts/build.js. Import this file directly into MusicFree.
var __getOwnPropNames = Object.getOwnPropertyNames;
var __commonJS = (cb, mod) => function __require() {
  return mod || (0, cb[__getOwnPropNames(cb)[0]])((mod = { exports: {} }).exports, mod), mod.exports;
};

// src/shared.js
var require_shared = __commonJS({
  "src/shared.js"(exports2, module2) {
    var axios2 = require("axios");
    var PAGE_SIZE2 = 30;
    var UA2 = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36";
    function text2(value, fallback) {
      if (value === void 0 || value === null || value === "") return fallback || "";
      return String(value);
    }
    function stripHtml2(value) {
      return text2(value).replace(/<[^>]*>/g, "").replace(/&amp;/g, "&").replace(/&lt;/g, "<").replace(/&gt;/g, ">").replace(/&quot;/g, '"').replace(/&#39;/g, "'").trim();
    }
    function parseDuration2(value) {
      if (typeof value === "number") {
        return value > 1e5 ? Math.floor(value / 1e3) : Math.floor(value);
      }
      const raw = text2(value);
      if (/^\d+:\d{1,2}$/.test(raw)) {
        const parts = raw.split(":").map(Number);
        return parts[0] * 60 + parts[1];
      }
      const parsed = Number(raw);
      return Number.isFinite(parsed) ? Math.floor(parsed) : void 0;
    }
    function artistNames(list, separator) {
      if (!Array.isArray(list)) return text2(list, "\u672A\u77E5\u6B4C\u624B");
      return list.map(function(artist) {
        return text2(artist && (artist.name || artist.title || artist.author_name));
      }).filter(Boolean).join(separator || "\u3001");
    }
    function formatLrcTime(seconds) {
      const value = Number(seconds) || 0;
      const minutes = Math.floor(value / 60);
      const rest = (value - minutes * 60).toFixed(2).padStart(5, "0");
      return "[" + String(minutes).padStart(2, "0") + ":" + rest + "]";
    }
    function decodeBase64(value) {
      if (!value) return "";
      try {
        return Buffer.from(value, "base64").toString("utf8");
      } catch (error) {
        return text2(value);
      }
    }
    function userVariables() {
      try {
        return env.getUserVariables() || {};
      } catch (error) {
        return {};
      }
    }
    function qualityLevel(quality) {
      return {
        low: "standard",
        standard: "standard",
        high: "exhigh",
        super: "lossless"
      }[quality] || "standard";
    }
    async function resolveMedia2(source, musicItem, quality) {
      const rid = text2(musicItem.sourceRid || musicItem.rid || musicItem.id);
      const response = await axios2.post(
        "https://musicserver.haitangw.cc/v1/music/resolve-url",
        { source, rid, level: qualityLevel(quality) },
        {
          headers: { "Content-Type": "application/json", Accept: "application/json" },
          timeout: 9e3
        }
      );
      const data = response.data && response.data.data;
      if (!data || !data.url) throw new Error("\u64AD\u653E\u5730\u5740\u89E3\u6790\u5931\u8D25");
      return { url: data.url, headers: data.playbackHeaders || data.headers || void 0 };
    }
    function normalizeComment(item) {
      const rawTime = Number(item.time);
      return {
        id: text2(item.id),
        nickName: text2(item.userName, "\u533F\u540D\u7528\u6237"),
        comment: text2(item.text),
        avatar: text2(item.avatar),
        like: Number(item.likedCount) || 0,
        createAt: Number.isFinite(rawTime) ? rawTime < 1e11 ? rawTime * 1e3 : rawTime : void 0,
        location: text2(item.location),
        replies: Array.isArray(item.reply) ? item.reply.map(function(reply) {
          const normalized = normalizeComment(reply);
          delete normalized.replies;
          return normalized;
        }) : []
      };
    }
    async function getComments2(source, musicItem, page) {
      const currentPage = Math.max(1, Number(page) || 1);
      const rid = text2(musicItem.sourceRid || musicItem.rid || musicItem.id);
      const response = await axios2.get(
        "https://music.haitangw.cc/pinglun/" + source + "pl.php",
        {
          params: { songmid: rid, type: "hot", page: currentPage, limit: 20 },
          headers: { "User-Agent": UA2 },
          timeout: 8e3
        }
      );
      const root = response.data || {};
      if (Number(root.code) !== 200) throw new Error(root.message || "\u8BC4\u8BBA\u52A0\u8F7D\u5931\u8D25");
      const data = root.data || {};
      const comments = Array.isArray(data.comments) ? data.comments : [];
      return {
        isEnd: currentPage >= Number(data.maxPage || 1) || comments.length < 20,
        data: comments.map(normalizeComment)
      };
    }
    function extractNumericId2(value) {
      const matches = text2(value).match(/\d+/g);
      if (!matches || !matches.length) throw new Error("\u65E0\u6CD5\u8BC6\u522B ID");
      return matches[matches.length - 1];
    }
    function createTopListGroups2(platformKey, groups) {
      return groups.map(function(group) {
        return {
          title: group.title,
          data: group.data.map(function(item) {
            const coverImg = "https://droidzf.github.io/musicfree/covers/" + platformKey + "-" + text2(item[0]) + ".png";
            return {
              id: text2(item[0]),
              bangId: text2(item[0]),
              title: item[1],
              description: item[2],
              coverImg,
              artwork: coverImg
            };
          })
        };
      });
    }
    module2.exports = {
      axios: axios2,
      PAGE_SIZE: PAGE_SIZE2,
      UA: UA2,
      text: text2,
      stripHtml: stripHtml2,
      parseDuration: parseDuration2,
      artistNames,
      formatLrcTime,
      decodeBase64,
      userVariables,
      resolveMedia: resolveMedia2,
      getComments: getComments2,
      extractNumericId: extractNumericId2,
      createTopListGroups: createTopListGroups2
    };
  }
});

// src/kugou.js
var {
  axios,
  PAGE_SIZE,
  UA,
  text,
  stripHtml,
  parseDuration,
  resolveMedia,
  getComments,
  extractNumericId,
  createTopListGroups
} = require_shared();
var TOP_LIST_GROUPS = [
  {
    title: "\u5DC5\u5CF0\u699C",
    data: [
      ["8888", "TOP500", "\u9177\u72D7\u97F3\u4E50\u7EFC\u5408\u70ED\u5EA6 TOP500\u3002"],
      ["6666", "\u98D9\u5347\u699C", "\u805A\u5408\u8FD1\u671F\u70ED\u5EA6\u5FEB\u901F\u4E0A\u5347\u7684\u6B4C\u66F2\u3002"],
      ["59703", "\u8702\u9E1F\u6D41\u884C\u97F3\u4E50\u699C", "\u5448\u73B0\u8702\u9E1F\u97F3\u4E50\u4F53\u7CFB\u4E2D\u7684\u6D41\u884C\u70ED\u6B4C\u3002"],
      ["52144", "\u6296\u97F3\u70ED\u6B4C\u699C", "\u6536\u5F55\u6296\u97F3\u8FD1\u671F\u70ED\u95E8\u97F3\u4E50\u3002"],
      ["52767", "\u5FEB\u624B\u70ED\u6B4C\u699C", "\u6536\u5F55\u5FEB\u624B\u8FD1\u671F\u70ED\u95E8\u97F3\u4E50\u3002"]
    ]
  },
  {
    title: "\u66F2\u98CE\u699C",
    data: [
      ["24971", "DJ\u70ED\u6B4C\u699C", "\u805A\u5408\u70ED\u95E8 DJ \u4E0E\u821E\u66F2\u4F5C\u54C1\u3002"],
      ["23784", "\u7F51\u7EDC\u7EA2\u6B4C\u699C", "\u805A\u5408\u8FD1\u671F\u7F51\u7EDC\u70ED\u95E8\u6B4C\u66F2\u3002"],
      ["44412", "\u8BF4\u5531\u5148\u950B\u699C", "\u805A\u5408\u70ED\u95E8\u8BF4\u5531\u4E0E\u5148\u950B\u4F5C\u54C1\u3002"],
      ["33160", "\u7535\u97F3\u699C", "\u805A\u5408\u70ED\u95E8\u7535\u5B50\u97F3\u4E50\u4F5C\u54C1\u3002"],
      ["51341", "\u6C11\u8C23\u699C", "\u805A\u5408\u70ED\u95E8\u6C11\u8C23\u4F5C\u54C1\u3002"],
      ["33162", "ACG\u65B0\u6B4C\u699C", "\u6536\u5F55\u8FD1\u671F\u70ED\u95E8 ACG \u65B0\u6B4C\u3002"],
      ["33165", "\u7CA4\u8BED\u91D1\u66F2\u699C", "\u805A\u5408\u70ED\u95E8\u7CA4\u8BED\u91D1\u66F2\u3002"],
      ["33166", "\u6B27\u7F8E\u91D1\u66F2\u699C", "\u805A\u5408\u6B27\u7F8E\u7ECF\u5178\u4E0E\u70ED\u95E8\u91D1\u66F2\u3002"],
      ["33163", "\u5F71\u89C6\u91D1\u66F2\u699C", "\u805A\u5408\u5F71\u89C6\u5267\u4E0E\u7EFC\u827A\u539F\u58F0\u91D1\u66F2\u3002"],
      ["51340", "\u4F24\u611F\u699C", "\u805A\u5408\u4F24\u611F\u6C1B\u56F4\u70ED\u95E8\u6B4C\u66F2\u3002"],
      ["59895", "R&B\u699C", "\u805A\u5408\u70ED\u95E8 R&B \u4F5C\u54C1\u3002"],
      ["59896", "\u6447\u6EDA\u699C", "\u805A\u5408\u70ED\u95E8\u6447\u6EDA\u4F5C\u54C1\u3002"],
      ["59897", "\u7235\u58EB\u699C", "\u805A\u5408\u70ED\u95E8\u7235\u58EB\u4F5C\u54C1\u3002"],
      ["59898", "\u4E61\u6751\u97F3\u4E50\u699C", "\u805A\u5408\u70ED\u95E8\u4E61\u6751\u97F3\u4E50\u3002"],
      ["59900", "\u7EAF\u97F3\u4E50\u699C", "\u805A\u5408\u70ED\u95E8\u7EAF\u97F3\u4E50\u4F5C\u54C1\u3002"],
      ["59899", "\u53E4\u5178\u699C", "\u805A\u5408\u70ED\u95E8\u53E4\u5178\u97F3\u4E50\u4F5C\u54C1\u3002"],
      ["33161", "\u53E4\u98CE\u65B0\u6B4C\u699C", "\u6536\u5F55\u8FD1\u671F\u70ED\u95E8\u53E4\u98CE\u65B0\u6B4C\u3002"]
    ]
  },
  {
    title: "\u5730\u533A\u699C",
    data: [
      ["31308", "\u5185\u5730\u699C", "\u805A\u5408\u4E2D\u56FD\u5185\u5730\u70ED\u95E8\u6B4C\u66F2\u3002"],
      ["31313", "\u9999\u6E2F\u5730\u533A\u699C", "\u805A\u5408\u4E2D\u56FD\u9999\u6E2F\u5730\u533A\u70ED\u95E8\u6B4C\u66F2\u3002"],
      ["54848", "\u53F0\u6E7E\u5730\u533A\u699C", "\u805A\u5408\u4E2D\u56FD\u53F0\u6E7E\u5730\u533A\u70ED\u95E8\u6B4C\u66F2\u3002"],
      ["31310", "\u6B27\u7F8E\u699C", "\u805A\u5408\u6B27\u7F8E\u5730\u533A\u70ED\u95E8\u6B4C\u66F2\u3002"],
      ["31311", "\u97E9\u56FD\u699C", "\u805A\u5408\u97E9\u56FD\u70ED\u95E8\u6B4C\u66F2\u3002"],
      ["31312", "\u65E5\u672C\u699C", "\u805A\u5408\u65E5\u672C\u70ED\u95E8\u6B4C\u66F2\u3002"],
      ["60170", "\u95FD\u5357\u8BED\u699C", "\u805A\u5408\u70ED\u95E8\u95FD\u5357\u8BED\u6B4C\u66F2\u3002"],
      ["36107", "\u5C0F\u8BED\u79CD\u70ED\u6B4C\u699C", "\u805A\u5408\u591A\u8BED\u79CD\u70ED\u95E8\u6B4C\u66F2\u3002"],
      ["60171", "\u8D8A\u5357\u8BED\u699C", "\u805A\u5408\u70ED\u95E8\u8D8A\u5357\u8BED\u6B4C\u66F2\u3002"],
      ["60172", "\u6CF0\u8BED\u699C", "\u805A\u5408\u70ED\u95E8\u6CF0\u8BED\u6B4C\u66F2\u3002"]
    ]
  },
  {
    title: "\u5E74\u4EE3\u699C",
    data: [
      ["49225", "80\u540E\u70ED\u6B4C\u699C", "\u805A\u5408\u6DF1\u53D7 80 \u540E\u542C\u4F17\u559C\u7231\u7684\u6B4C\u66F2\u3002"],
      ["49223", "90\u540E\u70ED\u6B4C\u699C", "\u805A\u5408\u6DF1\u53D7 90 \u540E\u542C\u4F17\u559C\u7231\u7684\u6B4C\u66F2\u3002"],
      ["49224", "00\u540E\u70ED\u6B4C\u699C", "\u805A\u5408\u6DF1\u53D7 00 \u540E\u542C\u4F17\u559C\u7231\u7684\u6B4C\u66F2\u3002"]
    ]
  },
  {
    title: "\u7279\u8272\u699C",
    data: [
      ["35811", "\u4F1A\u5458\u4E13\u4EAB\u699C", "\u805A\u5408\u9177\u72D7\u4F1A\u5458\u5173\u6CE8\u7684\u70ED\u95E8\u4F5C\u54C1\u3002"],
      ["37361", "\u96F7\u8FBE\u699C", "\u57FA\u4E8E\u5E73\u53F0\u8D8B\u52BF\u53D1\u73B0\u7684\u6F5C\u529B\u70ED\u6B4C\u3002"],
      ["21101", "\u5206\u4EAB\u699C", "\u6309\u7528\u6237\u5206\u4EAB\u70ED\u5EA6\u6574\u7406\u7684\u6B4C\u66F2\u3002"],
      ["46910", "\u7EFC\u827A\u65B0\u6B4C\u699C", "\u6536\u5F55\u8FD1\u671F\u7EFC\u827A\u8282\u76EE\u70ED\u95E8\u65B0\u6B4C\u3002"],
      ["30972", "\u9177\u72D7\u97F3\u4E50\u4EBA\u539F\u521B\u699C", "\u805A\u5408\u9177\u72D7\u97F3\u4E50\u4EBA\u539F\u521B\u4F5C\u54C1\u3002"],
      ["65234", "\u513F\u6B4C\u699C", "\u805A\u5408\u70ED\u95E8\u513F\u7AE5\u6B4C\u66F2\u3002"],
      ["22603", "5sing\u97F3\u4E50\u699C", "\u805A\u5408 5sing \u5E73\u53F0\u70ED\u95E8\u97F3\u4E50\u3002"],
      ["21335", "\u7E41\u661F\u97F3\u4E50\u699C", "\u805A\u5408\u7E41\u661F\u97F3\u4E50\u70ED\u95E8\u4F5C\u54C1\u3002"]
    ]
  },
  {
    title: "\u5168\u7403\u699C",
    data: [
      ["4681", "\u7F8E\u56FDBillBoard\u699C", "\u6536\u5F55\u7F8E\u56FD Billboard \u70ED\u95E8\u4F5C\u54C1\u3002"],
      ["25028", "Beatport\u7535\u5B50\u821E\u66F2\u699C", "\u6536\u5F55 Beatport \u70ED\u95E8\u7535\u5B50\u821E\u66F2\u3002"],
      ["4680", "\u82F1\u56FD\u5355\u66F2\u699C", "\u6536\u5F55\u82F1\u56FD\u70ED\u95E8\u5355\u66F2\u3002"],
      ["38623", "\u97E9\u56FDMelon\u97F3\u4E50\u699C", "\u6536\u5F55\u97E9\u56FD Melon \u70ED\u95E8\u97F3\u4E50\u3002"],
      ["42807", "joox\u672C\u5730\u70ED\u6B4C\u699C", "\u6536\u5F55 JOOX \u672C\u5730\u70ED\u95E8\u6B4C\u66F2\u3002"],
      ["4673", "\u65E5\u672C\u516C\u4FE1\u699C", "\u6536\u5F55\u65E5\u672C\u516C\u4FE1\u699C\u70ED\u95E8\u4F5C\u54C1\u3002"],
      ["46868", "\u65E5\u672CSPACE SHOWER\u699C", "\u6536\u5F55 SPACE SHOWER \u70ED\u95E8\u4F5C\u54C1\u3002"],
      ["42808", "KKBOX\u98CE\u4E91\u699C", "\u6536\u5F55 KKBOX \u98CE\u4E91\u70ED\u95E8\u4F5C\u54C1\u3002"]
    ]
  }
];
var SHEET_TAGS = [
  ["5", "\u63A8\u8350"],
  ["6", "\u6700\u70ED"],
  ["7", "\u6700\u65B0"],
  ["3", "\u70ED\u85CF"],
  ["8", "\u98D9\u5347"]
];
function splitFilename(value) {
  const raw = stripHtml(value);
  const index = raw.indexOf(" - ");
  if (index < 0) return { artist: "\u672A\u77E5\u6B4C\u624B", title: raw };
  return { artist: raw.slice(0, index), title: raw.slice(index + 3) };
}
function mapMusic(item) {
  const rid = text(item.hash || item.FileHash || item.Hash || item.HASH);
  const names = splitFilename(item.filename || item.FileName || item.SongName || item.songname);
  const cover = text(
    item.album_sizable_cover || item.Image || item.image || item.trans_param && item.trans_param.union_cover
  ).replace("{size}", "400");
  return {
    id: rid,
    title: stripHtml(item.songname || item.SongName || names.title),
    artist: stripHtml(item.singername || item.SingerName || names.artist),
    album: stripHtml(item.album_name || item.AlbumName || item.remark),
    duration: parseDuration(item.duration || item.Duration || item.timelength),
    artwork: cover,
    sourceRid: rid
  };
}
async function search(query, page, type) {
  if (type !== "music") return { isEnd: true, data: [] };
  const currentPage = Math.max(1, Number(page) || 1);
  const response = await axios.get("https://songsearch.kugou.com/song_search_v2", {
    params: {
      keyword: query,
      page: currentPage,
      pagesize: PAGE_SIZE,
      platform: "WebFilter",
      filter: 2,
      iscorrection: 1,
      privilege_filter: 0,
      area_code: 1
    },
    headers: { "User-Agent": UA, Referer: "https://www.kugou.com/" },
    timeout: 8e3
  });
  const root = response.data || {};
  const list = root.data && (root.data.lists || root.data.list) || [];
  return { isEnd: list.length < PAGE_SIZE, data: list.map(mapMusic) };
}
async function getLyric(musicItem) {
  const rid = text(musicItem.sourceRid || musicItem.id);
  const response = await axios.get("https://m.kugou.com/app/i/krc.php", {
    params: { cmd: 100, hash: rid, timelength: 1 },
    headers: { "User-Agent": UA, Referer: "https://m.kugou.com/" },
    responseType: "text",
    timeout: 8e3
  });
  return { rawLrc: text(response.data) };
}
async function getMusicInfo(musicItem) {
  const rid = text(musicItem.sourceRid || musicItem.id);
  const timestamp = Math.floor(Date.now() / 1e3);
  const response = await axios.post(
    "https://gateway.kugou.com/goodsmstore/v1/get_res_privilege?appid=1005&clientver=20049&clienttime=" + timestamp + "&mid=123",
    {
      behavior: "play",
      clientver: "20049",
      resource: [{ id: 0, type: "audio", hash: rid }],
      area_code: "1",
      quality: "128",
      qualities: ["128", "320", "flac", "high", "dolby", "viper_atmos", "viper_tape", "viper_clear"]
    },
    {
      headers: { "User-Agent": "Android/10 KugouMusic/13.0.0", "Content-Type": "application/json" },
      timeout: 8e3
    }
  );
  const item = response.data && response.data.data && response.data.data[0];
  const info = item && item.info;
  if (!item || !info) return {};
  return {
    title: splitFilename(item.name).title,
    artist: text(item.singername),
    album: text(item.albumname),
    artwork: text(info.image).replace("{size}", "720"),
    duration: parseDuration(info.duration),
    sourceRid: rid
  };
}
async function getTopListDetail(topListItem, page) {
  const currentPage = Math.max(1, Number(page) || 1);
  const response = await axios.get("http://mobilecdnbj.kugou.com/api/v3/rank/song", {
    params: {
      version: 9108,
      ranktype: 1,
      plat: 0,
      pagesize: 100,
      area_code: 1,
      page: currentPage,
      rankid: topListItem.bangId || topListItem.id,
      with_res_tag: 0,
      show_portrait_mv: 1
    },
    headers: { "User-Agent": UA, Referer: "https://www.kugou.com/" },
    timeout: 9e3
  });
  const data = response.data && response.data.data || {};
  const list = data.info || [];
  return {
    isEnd: currentPage * 100 >= Number(data.total || 0) || list.length < 100,
    musicList: list.map(mapMusic)
  };
}
async function getRecommendSheetsByTag(tag, page) {
  const currentPage = Math.max(1, Number(page) || 1);
  const response = await axios.get("http://www2.kugou.kugou.com/yueku/v9/special/getSpecial", {
    params: {
      is_ajax: 1,
      cdn: "cdn",
      t: text(tag && tag.id, "5"),
      c: "",
      p: currentPage
    },
    headers: { "User-Agent": UA, Referer: "https://www.kugou.com/" },
    timeout: 8e3
  });
  const list = response.data && response.data.special_db || [];
  return {
    isEnd: list.length < 20,
    data: list.map(function(item) {
      return {
        id: text(item.specialid),
        title: text(item.specialname),
        artist: text(item.nickname || item.author),
        artwork: text(item.img).replace("{size}", "400"),
        description: text(item.intro),
        worksNum: Number(item.song_count) || void 0,
        playCount: Number(text(item.total_play_count).replace(/[^\d.]/g, "")) || void 0,
        globalCollectionId: text(item.global_collection_id)
      };
    })
  };
}
function parseEmbeddedSongs(html) {
  const match = text(html).match(/var data=(\[[\s\S]*?\])\s*,\s*specialData\s*=/);
  if (!match) throw new Error("\u9177\u72D7\u6B4C\u5355\u9875\u9762\u672A\u627E\u5230\u6B4C\u66F2\u6570\u636E");
  return JSON.parse(match[1]);
}
async function getMusicSheetInfo(sheetItem, page) {
  const currentPage = Math.max(1, Number(page) || 1);
  const base = "https://m.kugou.com/plist/list/" + encodeURIComponent(sheetItem.id) + "/";
  if (currentPage === 1) {
    const response2 = await axios.get(base, {
      params: { json: "true" },
      headers: { "User-Agent": UA, Referer: "https://m.kugou.com/" },
      timeout: 9e3
    });
    const root = response2.data || {};
    const listRoot = root.list && root.list.list || {};
    const info = root.info && root.info.list;
    const songs = listRoot.info || [];
    return {
      isEnd: Number(listRoot.total || 0) <= songs.length,
      musicList: songs.map(mapMusic),
      sheetItem: info ? {
        title: text(info.specialname || sheetItem.title),
        artist: text(info.nickname),
        artwork: text(info.imgurl).replace("{size}", "400"),
        description: text(info.intro),
        worksNum: Number(info.songcount) || void 0,
        playCount: Number(info.playcount) || void 0
      } : void 0
    };
  }
  const response = await axios.get(base + "?json=true&page=" + currentPage, {
    headers: { "User-Agent": UA, Referer: "https://m.kugou.com/" },
    responseType: "text",
    timeout: 9e3
  });
  const allSongs = parseEmbeddedSongs(response.data);
  const start = (currentPage - 1) * 10;
  const pageSongs = allSongs.slice(start, start + 10);
  return { isEnd: start + pageSongs.length >= allSongs.length, musicList: pageSongs.map(mapMusic) };
}
async function importMusicSheet(urlLike) {
  const id = extractNumericId(urlLike);
  const response = await axios.get(
    "https://m.kugou.com/plist/list/" + encodeURIComponent(id) + "/?json=true&page=2",
    {
      headers: { "User-Agent": UA, Referer: "https://m.kugou.com/" },
      responseType: "text",
      timeout: 9e3
    }
  );
  return parseEmbeddedSongs(response.data).map(mapMusic);
}
module.exports = {
  platform: "\u9177\u72D7\u97F3\u4E50",
  version: "1.2.1",
  srcUrl: "https://droidzf.github.io/musicfree/kugou.js",
  author: "zero",
  description: "\u72EC\u7ACB\u9177\u72D7\u97F3\u4E50\u63D2\u4EF6\uFF1A\u641C\u7D22\u3001\u64AD\u653E\u3001\u6B4C\u8BCD\u300151 \u4E2A\u699C\u5355\u3001\u63A8\u8350\u6B4C\u5355\u3001\u6B4C\u5355\u8BE6\u60C5\u548C\u8BC4\u8BBA\u3002",
  cacheControl: "no-store",
  supportedSearchType: ["music"],
  hints: { importMusicSheet: ["\u652F\u6301\u9177\u72D7\u6B4C\u5355\u94FE\u63A5\u6216\u7EAF\u6570\u5B57\u6B4C\u5355 ID\u3002"] },
  search,
  getMediaSource: function(musicItem, quality) {
    return resolveMedia("kg", musicItem, quality);
  },
  getLyric,
  getMusicInfo,
  getTopLists: function() {
    return Promise.resolve(createTopListGroups("kugou", TOP_LIST_GROUPS));
  },
  getTopListDetail,
  getRecommendSheetTags: function() {
    return Promise.resolve({
      pinned: [{ id: "5", title: "\u63A8\u8350" }],
      data: [
        {
          title: "\u6B4C\u5355\u5206\u7C7B",
          data: SHEET_TAGS.map(function(item) {
            return { id: item[0], title: item[1] };
          })
        }
      ]
    });
  },
  getRecommendSheetsByTag,
  getMusicSheetInfo,
  importMusicSheet,
  getMusicComments: function(musicItem, page) {
    return getComments("kg", musicItem, page);
  }
};
