// Generated by scripts/build.js. Import this file directly into MusicFree.
var __getOwnPropNames = Object.getOwnPropertyNames;
var __commonJS = (cb, mod) => function __require() {
  return mod || (0, cb[__getOwnPropNames(cb)[0]])((mod = { exports: {} }).exports, mod), mod.exports;
};

// src/shared.js
var require_shared = __commonJS({
  "src/shared.js"(exports2, module2) {
    var axios2 = require("axios");
    var PAGE_SIZE2 = 30;
    var UA2 = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36";
    function text2(value, fallback) {
      if (value === void 0 || value === null || value === "") return fallback || "";
      return String(value);
    }
    function stripHtml2(value) {
      return text2(value).replace(/<[^>]*>/g, "").replace(/&amp;/g, "&").replace(/&lt;/g, "<").replace(/&gt;/g, ">").replace(/&quot;/g, '"').replace(/&#39;/g, "'").trim();
    }
    function toHttps2(value, size) {
      return text2(value).replace(/^http:\/\//i, "https://").replace(/\{size\}/g, text2(size, "400"));
    }
    function parseJsonp(value) {
      const raw = text2(value).trim();
      const start = raw.indexOf("(");
      const end = raw.lastIndexOf(")");
      return JSON.parse(start >= 0 && end > start ? raw.slice(start + 1, end) : raw);
    }
    function parseDuration2(value) {
      if (typeof value === "number") {
        return value > 1e5 ? Math.floor(value / 1e3) : Math.floor(value);
      }
      const raw = text2(value);
      if (/^\d+:\d{1,2}$/.test(raw)) {
        const parts = raw.split(":").map(Number);
        return parts[0] * 60 + parts[1];
      }
      const parsed = Number(raw);
      return Number.isFinite(parsed) ? Math.floor(parsed) : void 0;
    }
    function artistNames(list, separator) {
      if (!Array.isArray(list)) return text2(list, "\u672A\u77E5\u6B4C\u624B");
      return list.map(function(artist) {
        return text2(artist && (artist.name || artist.title || artist.author_name));
      }).filter(Boolean).join(separator || "\u3001");
    }
    function formatLrcTime2(seconds) {
      const value = Number(seconds) || 0;
      const minutes = Math.floor(value / 60);
      const rest = (value - minutes * 60).toFixed(2).padStart(5, "0");
      return "[" + String(minutes).padStart(2, "0") + ":" + rest + "]";
    }
    function decodeBase64(value) {
      if (!value) return "";
      try {
        return Buffer.from(value, "base64").toString("utf8");
      } catch (error) {
        return text2(value);
      }
    }
    function userVariables() {
      try {
        return env.getUserVariables() || {};
      } catch (error) {
        return {};
      }
    }
    function qualityLevel(quality) {
      return {
        low: "standard",
        standard: "standard",
        high: "exhigh",
        super: "lossless"
      }[quality] || "standard";
    }
    async function resolveMedia2(source, musicItem, quality) {
      const rid = text2(musicItem.sourceRid || musicItem.rid || musicItem.id);
      const response = await axios2.post(
        "https://musicserver.haitangw.cc/v1/music/resolve-url",
        { source, rid, level: qualityLevel(quality) },
        {
          headers: { "Content-Type": "application/json", Accept: "application/json" },
          timeout: 9e3
        }
      );
      const data = response.data && response.data.data;
      if (!data || !data.url) throw new Error("\u64AD\u653E\u5730\u5740\u89E3\u6790\u5931\u8D25");
      return { url: data.url, headers: data.playbackHeaders || data.headers || void 0 };
    }
    function normalizeComment(item) {
      const rawTime = Number(item.time);
      return {
        id: text2(item.id),
        nickName: text2(item.userName, "\u533F\u540D\u7528\u6237"),
        comment: text2(item.text),
        avatar: text2(item.avatar),
        like: Number(item.likedCount) || 0,
        createAt: Number.isFinite(rawTime) ? rawTime < 1e11 ? rawTime * 1e3 : rawTime : void 0,
        location: text2(item.location),
        replies: Array.isArray(item.reply) ? item.reply.map(function(reply) {
          const normalized = normalizeComment(reply);
          delete normalized.replies;
          return normalized;
        }) : []
      };
    }
    async function getComments2(source, musicItem, page) {
      const currentPage = Math.max(1, Number(page) || 1);
      const rid = text2(musicItem.sourceRid || musicItem.rid || musicItem.id);
      const response = await axios2.get(
        "https://music.haitangw.cc/pinglun/" + source + "pl.php",
        {
          params: { songmid: rid, type: "hot", page: currentPage, limit: 20 },
          headers: { "User-Agent": UA2 },
          timeout: 8e3
        }
      );
      const root = response.data || {};
      if (Number(root.code) !== 200) throw new Error(root.message || "\u8BC4\u8BBA\u52A0\u8F7D\u5931\u8D25");
      const data = root.data || {};
      const comments = Array.isArray(data.comments) ? data.comments : [];
      return {
        isEnd: currentPage >= Number(data.maxPage || 1) || comments.length < 20,
        data: comments.map(normalizeComment)
      };
    }
    function extractNumericId2(value) {
      const matches = text2(value).match(/\d+/g);
      if (!matches || !matches.length) throw new Error("\u65E0\u6CD5\u8BC6\u522B ID");
      return matches[matches.length - 1];
    }
    module2.exports = {
      axios: axios2,
      PAGE_SIZE: PAGE_SIZE2,
      UA: UA2,
      text: text2,
      stripHtml: stripHtml2,
      toHttps: toHttps2,
      parseJsonp,
      parseDuration: parseDuration2,
      artistNames,
      formatLrcTime: formatLrcTime2,
      decodeBase64,
      userVariables,
      resolveMedia: resolveMedia2,
      getComments: getComments2,
      extractNumericId: extractNumericId2
    };
  }
});

// src/kuwo.js
var {
  axios,
  PAGE_SIZE,
  UA,
  text,
  stripHtml,
  toHttps,
  parseDuration,
  formatLrcTime,
  resolveMedia,
  getComments,
  extractNumericId
} = require_shared();
var cheerio = require("cheerio");
var KUWO_SECRET_COOKIE = "Hm_Iuvt_cdb524f42f23cer9b268564v7y735ewrq2324";
function createKuwoSecret(token, key) {
  let digits = "";
  for (let index = 0; index < key.length; index += 1) {
    digits += key.charCodeAt(index).toString();
  }
  const step = Math.floor(digits.length / 5);
  const multiplier = parseInt(
    digits.charAt(step) + digits.charAt(step * 2) + digits.charAt(step * 3) + digits.charAt(step * 4) + digits.charAt(step * 5),
    10
  );
  const increment = Math.ceil(key.length / 2);
  const modulus = Math.pow(2, 31) - 1;
  let seed = Math.round(1e9 * Math.random()) % 1e8;
  let mixed = digits + seed;
  while (mixed.length > 10) {
    mixed = (parseInt(mixed.substring(0, 10), 10) + parseInt(mixed.substring(10), 10)).toString();
  }
  let state = (multiplier * Number(mixed) + increment) % modulus;
  let result = "";
  for (let index = 0; index < token.length; index += 1) {
    const value = token.charCodeAt(index) ^ Math.floor(state / modulus * 255);
    result += (value < 16 ? "0" : "") + value.toString(16);
    state = (multiplier * state + increment) % modulus;
  }
  let suffix = seed.toString(16);
  while (suffix.length < 8) suffix = "0" + suffix;
  return result + suffix;
}
function extractKuwoSession(response) {
  const headers = response && response.headers || {};
  const rawCookie = headers["set-cookie"] || headers["Set-Cookie"] || "";
  const cookieText = Array.isArray(rawCookie) ? rawCookie.join(";") : text(rawCookie);
  const match = new RegExp(KUWO_SECRET_COOKIE + "=([^;]+)", "i").exec(cookieText);
  return match ? match[1] : "";
}
function createKuwoSessionToken() {
  const alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
  let token = "";
  for (let index = 0; index < 32; index += 1) {
    token += alphabet.charAt(Math.floor(Math.random() * alphabet.length));
  }
  return token;
}
function kuwoWebHeaders(token) {
  return {
    Secret: createKuwoSecret(token, KUWO_SECRET_COOKIE),
    Cookie: KUWO_SECRET_COOKIE + "=" + token,
    Referer: "https://www.kuwo.cn/playlists",
    "User-Agent": UA
  };
}
var playlistPageCache;
var playlistPageCacheAt = 0;
function createNuxtValueParser(source, variables) {
  let index = 0;
  function skipWhitespace() {
    while (/\s/.test(source.charAt(index))) index += 1;
  }
  function parseString() {
    const start = index;
    index += 1;
    while (index < source.length) {
      if (source.charAt(index) === "\\") {
        index += 2;
        continue;
      }
      if (source.charAt(index) === '"') {
        index += 1;
        return JSON.parse(source.slice(start, index));
      }
      index += 1;
    }
    throw new Error("\u9177\u6211\u6B4C\u5355\u9875\u9762\u5B57\u7B26\u4E32\u89E3\u6790\u5931\u8D25");
  }
  function parseIdentifier() {
    const start = index;
    while (/[A-Za-z0-9_$]/.test(source.charAt(index))) index += 1;
    return source.slice(start, index);
  }
  function parseNumber() {
    const start = index;
    while (/[0-9eE+\-.]/.test(source.charAt(index))) index += 1;
    const value = Number(source.slice(start, index));
    if (!Number.isFinite(value)) throw new Error("\u9177\u6211\u6B4C\u5355\u9875\u9762\u6570\u5B57\u89E3\u6790\u5931\u8D25");
    return value;
  }
  function parseArray() {
    const result = [];
    index += 1;
    skipWhitespace();
    if (source.charAt(index) === "]") {
      index += 1;
      return result;
    }
    while (index < source.length) {
      result.push(parseValue());
      skipWhitespace();
      if (source.charAt(index) === "]") {
        index += 1;
        return result;
      }
      if (source.charAt(index) !== ",") throw new Error("\u9177\u6211\u6B4C\u5355\u9875\u9762\u6570\u7EC4\u89E3\u6790\u5931\u8D25");
      index += 1;
    }
    throw new Error("\u9177\u6211\u6B4C\u5355\u9875\u9762\u6570\u7EC4\u672A\u95ED\u5408");
  }
  function parseObject() {
    const result = {};
    index += 1;
    skipWhitespace();
    if (source.charAt(index) === "}") {
      index += 1;
      return result;
    }
    while (index < source.length) {
      skipWhitespace();
      const key = source.charAt(index) === '"' ? parseString() : parseIdentifier();
      skipWhitespace();
      if (!key || source.charAt(index) !== ":") {
        throw new Error("\u9177\u6211\u6B4C\u5355\u9875\u9762\u5BF9\u8C61\u89E3\u6790\u5931\u8D25");
      }
      index += 1;
      result[key] = parseValue();
      skipWhitespace();
      if (source.charAt(index) === "}") {
        index += 1;
        return result;
      }
      if (source.charAt(index) !== ",") throw new Error("\u9177\u6211\u6B4C\u5355\u9875\u9762\u5BF9\u8C61\u89E3\u6790\u5931\u8D25");
      index += 1;
    }
    throw new Error("\u9177\u6211\u6B4C\u5355\u9875\u9762\u5BF9\u8C61\u672A\u95ED\u5408");
  }
  function parseValue() {
    skipWhitespace();
    const current = source.charAt(index);
    if (current === '"') return parseString();
    if (current === "[") return parseArray();
    if (current === "{") return parseObject();
    if (current === "-" || /[0-9]/.test(current)) return parseNumber();
    const identifier = parseIdentifier();
    if (identifier === "true") return true;
    if (identifier === "false") return false;
    if (identifier === "null") return null;
    if (Object.prototype.hasOwnProperty.call(variables, identifier)) {
      return variables[identifier];
    }
    throw new Error("\u9177\u6211\u6B4C\u5355\u9875\u9762\u5305\u542B\u672A\u77E5\u53D8\u91CF: " + identifier);
  }
  return function(start) {
    index = start;
    const value = parseValue();
    return { value, end: index };
  };
}
function parseKuwoPlaylistPage(rawHtml) {
  const $ = cheerio.load(text(rawHtml));
  let script = "";
  $("script").each(function() {
    const content = $(this).html() || "";
    if (!script && content.indexOf("window.__NUXT__=") >= 0) script = content;
  });
  if (!script) throw new Error("\u9177\u6211\u6B4C\u5355\u9875\u9762\u7F3A\u5C11\u5B98\u65B9\u6570\u636E");
  const functionMatch = /window\.__NUXT__=\(function\(([^)]*)\)\{return\s*/.exec(script);
  const invocationIndex = script.lastIndexOf("}(");
  const argumentsEnd = script.lastIndexOf("));");
  if (!functionMatch || invocationIndex < 0 || argumentsEnd <= invocationIndex) {
    throw new Error("\u9177\u6211\u6B4C\u5355\u9875\u9762\u683C\u5F0F\u5DF2\u53D8\u5316");
  }
  const parameterNames = functionMatch[1].split(",").filter(Boolean);
  const argumentValues = JSON.parse(
    "[" + script.slice(invocationIndex + 2, argumentsEnd) + "]"
  );
  const variables = {};
  parameterNames.forEach(function(name, parameterIndex) {
    variables[name] = argumentValues[parameterIndex];
  });
  const parseAt = createNuxtValueParser(script, variables);
  const playListMarker = "playList:";
  const playListIndex = script.indexOf(playListMarker, functionMatch.index);
  if (playListIndex < 0) throw new Error("\u9177\u6211\u6B4C\u5355\u9875\u9762\u7F3A\u5C11\u63A8\u8350\u5217\u8868");
  const playListResult = parseAt(playListIndex + playListMarker.length);
  const totalMarker = ",total:";
  const totalIndex = script.indexOf(totalMarker, playListResult.end);
  const totalResult = totalIndex < 0 ? { value: 0 } : parseAt(totalIndex + totalMarker.length);
  const tagListMarker = "tagList:";
  const tagListIndex = script.indexOf(tagListMarker, playListResult.end);
  if (tagListIndex < 0) throw new Error("\u9177\u6211\u6B4C\u5355\u9875\u9762\u7F3A\u5C11\u5206\u7C7B\u6807\u7B7E");
  const tagListResult = parseAt(tagListIndex + tagListMarker.length);
  return {
    playList: Array.isArray(playListResult.value) ? playListResult.value : [],
    total: Number(totalResult.value) || 0,
    tagList: Array.isArray(tagListResult.value) ? tagListResult.value : []
  };
}
async function getKuwoPlaylistPageData() {
  const now = Date.now();
  if (playlistPageCache && now - playlistPageCacheAt < 5 * 60 * 1e3) {
    return playlistPageCache;
  }
  const response = await axios.get("https://www.kuwo.cn/playlists", {
    headers: {
      Accept: "text/html,application/xhtml+xml",
      Referer: "https://www.kuwo.cn/",
      "User-Agent": UA
    },
    responseType: "text",
    timeout: 8e3
  });
  const parsed = parseKuwoPlaylistPage(response.data);
  if (!parsed.playList.length || !parsed.tagList.length) {
    throw new Error("\u9177\u6211\u5B98\u65B9\u63A8\u8350\u6B4C\u5355\u4E3A\u7A7A");
  }
  parsed.sessionToken = extractKuwoSession(response) || createKuwoSessionToken();
  playlistPageCache = parsed;
  playlistPageCacheAt = now;
  return parsed;
}
function mapRecommendSheet(item) {
  return {
    id: text(item.id),
    title: text(item.name),
    artist: text(item.uname),
    artwork: toHttps(item.img),
    description: text(item.desc || item.info),
    worksNum: Number(item.total) || void 0,
    playCount: Number(item.listencnt) || void 0
  };
}
function artwork(item) {
  const path = text(item.web_albumpic_short || item.WEB_ALBUMPIC_SHORT);
  if (!path) return toHttps(item.pic || item.PIC || item.albumpic);
  if (/^https?:\/\//i.test(path)) return toHttps(path);
  return "https://img1.kuwo.cn/star/albumcover/300/" + path.replace(/^\//, "");
}
function mapMusic(item) {
  const rid = text(
    item.rid || item.DC_TARGETID || item.musicrid || item.MUSICRID || item.id
  ).replace(
    /^MUSIC_/,
    ""
  );
  return {
    id: rid,
    title: stripHtml(item.name || item.songname || item.SONGNAME),
    artist: stripHtml(item.artist || item.ARTIST || "\u672A\u77E5\u6B4C\u624B"),
    album: stripHtml(item.album || item.ALBUM),
    duration: parseDuration(item.duration || item.DURATION),
    artwork: artwork(item),
    sourceRid: rid
  };
}
async function getTopLists() {
  const response = await axios.get("https://wapi.kuwo.cn/api/pc/bang/list", {
    headers: { "User-Agent": UA, Referer: "https://www.kuwo.cn/rankList" },
    timeout: 8e3
  });
  const root = response.data && response.data.data || response.data || {};
  return (root.child || []).map(function(group) {
    return {
      title: text(group.disname || group.name),
      data: (group.child || []).map(function(item) {
        const coverImg = toHttps(item.pic5 || item.pic2 || item.pic);
        return {
          id: text(item.sourceid || item.id),
          bangId: text(item.sourceid || item.id),
          title: text(item.disname || item.name),
          description: text(item.intro || item.tips),
          coverImg,
          artwork: coverImg,
          updateTime: text(item.pubTime)
        };
      })
    };
  });
}
async function search(query, page, type) {
  if (type !== "music") return { isEnd: true, data: [] };
  const currentPage = Math.max(1, Number(page) || 1);
  const response = await axios.get("http://search.kuwo.cn/r.s", {
    params: {
      client: "kt",
      all: query,
      pn: currentPage - 1,
      rn: PAGE_SIZE,
      uid: "794762570",
      ver: "kwplayer_ar_9.2.2.1",
      ft: "music",
      cluster: 0,
      strategy: 2012,
      encoding: "utf8",
      rformat: "json",
      mobi: 1
    },
    headers: { "User-Agent": UA },
    timeout: 8e3
  });
  const root = response.data || {};
  const list = root.abslist || root.data && root.data.list || [];
  return { isEnd: list.length < PAGE_SIZE, data: list.map(mapMusic) };
}
async function getLyric(musicItem) {
  const rid = text(musicItem.sourceRid || musicItem.id);
  const response = await axios.get("https://wapi.kuwo.cn/openapi/v1/www/lyric/getlyric", {
    params: { musicId: rid, httpsStatus: 1 },
    headers: { "User-Agent": UA, Referer: "https://www.kuwo.cn/" },
    timeout: 8e3
  });
  const list = response.data && response.data.data && response.data.data.lrclist || response.data && response.data.lrclist || [];
  return {
    rawLrc: list.map(function(line) {
      return formatLrcTime(line.time) + text(line.lineLyric || line.line);
    }).join("\n")
  };
}
async function getMusicInfo(musicItem) {
  const rid = text(musicItem.sourceRid || musicItem.id);
  const response = await axios.get("http://musicpay.kuwo.cn/music.pay", {
    params: { op: "query", action: "play", ids: rid },
    headers: { "User-Agent": UA },
    timeout: 8e3
  });
  const item = response.data && response.data.songs && response.data.songs[0];
  if (!item) return {};
  return {
    title: text(item.name),
    artist: text(item.artist),
    album: text(item.album),
    artwork: text(item.musicPic || item.albumPic),
    duration: parseDuration(item.duration),
    sourceRid: rid
  };
}
async function getTopListDetail(topListItem, page) {
  const currentPage = Math.max(1, Number(page) || 1);
  const response = await axios.get("https://wapi.kuwo.cn/api/www/bang/bang/musicList", {
    params: { bangId: topListItem.bangId || topListItem.id, pn: currentPage, rn: PAGE_SIZE },
    headers: { "User-Agent": UA, Referer: "https://www.kuwo.cn/" },
    timeout: 8e3
  });
  const root = response.data && response.data.data || {};
  const list = root.musicList || [];
  const result = { isEnd: list.length < PAGE_SIZE, musicList: list.map(mapMusic) };
  if (currentPage === 1) {
    const coverImg = text(topListItem.coverImg || topListItem.artwork) || text(root.img);
    result.topListItem = { coverImg, artwork: coverImg };
  }
  return result;
}
async function getRecommendSheetsByTag(tag, page) {
  const currentPage = Math.max(1, Number(page) || 1);
  const tagId = text(tag && tag.id, "__recommend__");
  if (tagId === "__recommend__" && currentPage === 1) {
    const officialPage2 = await getKuwoPlaylistPageData();
    return {
      isEnd: officialPage2.playList.length < 20 || officialPage2.playList.length >= officialPage2.total,
      data: officialPage2.playList.map(mapRecommendSheet)
    };
  }
  const officialPage = await getKuwoPlaylistPageData();
  const endpoint = tagId === "__recommend__" ? "https://www.kuwo.cn/api/www/classify/playlist/getRcmPlayList" : "https://www.kuwo.cn/api/www/classify/playlist/getTagPlayList";
  const params = { pn: currentPage, rn: 20, httpsStatus: 1, plat: "web_www" };
  if (tagId === "__recommend__") params.order = "new";
  else params.id = tagId;
  const response = await axios.get(endpoint, {
    params,
    headers: kuwoWebHeaders(officialPage.sessionToken),
    timeout: 8e3
  });
  const data = response.data && response.data.data || {};
  const list = data.data || [];
  return {
    isEnd: currentPage * 20 >= Number(data.total || 0) || list.length < 20,
    data: list.map(mapRecommendSheet)
  };
}
async function getMusicSheetInfo(sheetItem, page) {
  const currentPage = Math.max(1, Number(page) || 1);
  const pageSize = 30;
  const response = await axios.get("http://nplserver.kuwo.cn/pl.svc", {
    params: {
      op: "getlistinfo",
      pid: sheetItem.id,
      pn: currentPage - 1,
      rn: pageSize,
      encode: "utf8",
      keyset: "pl2012",
      vipver: "MUSIC_9.1.1.2_BCS2",
      newver: 1
    },
    headers: { "User-Agent": UA },
    timeout: 9e3
  });
  const data = response.data || {};
  const musicList = data.musiclist || data.musicList || [];
  const result = {
    isEnd: currentPage * pageSize >= Number(data.total || 0) || musicList.length < pageSize,
    musicList: musicList.map(mapMusic)
  };
  if (currentPage === 1) {
    result.sheetItem = {
      title: text(data.title || sheetItem.title),
      artist: text(data.uname),
      artwork: toHttps(data.pic),
      description: text(data.info),
      worksNum: Number(data.total) || musicList.length,
      playCount: Number(data.playnum) || void 0
    };
  }
  return result;
}
async function getRecommendSheetTags() {
  const officialPage = await getKuwoPlaylistPageData();
  const groups = officialPage.tagList;
  return {
    pinned: [{ id: "__recommend__", title: "\u7CBE\u9009\u6B4C\u5355" }],
    data: groups.filter(function(group) {
      return Array.isArray(group.data) && group.data.length > 0;
    }).map(function(group) {
      return {
        title: text(group.name),
        data: group.data.map(function(item) {
          return { id: text(item.id), title: text(item.name) };
        })
      };
    })
  };
}
async function importMusicSheet(urlLike) {
  const id = extractNumericId(urlLike);
  return (await getMusicSheetInfo({ id, title: "\u5BFC\u5165\u6B4C\u5355" }, 1)).musicList;
}
module.exports = {
  platform: "\u9177\u6211\u97F3\u4E50",
  version: "1.3.2",
  srcUrl: "https://droidzf.github.io/musicfree/kuwo.js",
  author: "zero",
  description: "\u72EC\u7ACB\u9177\u6211\u97F3\u4E50\u63D2\u4EF6\uFF1A\u641C\u7D22\u3001\u64AD\u653E\u3001\u6B4C\u8BCD\u3001\u699C\u5355\u3001\u63A8\u8350\u6B4C\u5355\u3001\u6B4C\u5355\u8BE6\u60C5\u548C\u8BC4\u8BBA\u3002",
  cacheControl: "no-store",
  supportedSearchType: ["music"],
  hints: { importMusicSheet: ["\u652F\u6301\u9177\u6211\u6B4C\u5355\u94FE\u63A5\u6216\u7EAF\u6570\u5B57\u6B4C\u5355 ID\u3002"] },
  search,
  getMediaSource: function(musicItem, quality) {
    return resolveMedia("kw", musicItem, quality);
  },
  getLyric,
  getMusicInfo,
  getTopLists,
  getTopListDetail,
  getRecommendSheetTags,
  getRecommendSheetsByTag,
  getMusicSheetInfo,
  importMusicSheet,
  getMusicComments: function(musicItem, page) {
    return getComments("kw", musicItem, page);
  }
};
