// Generated by scripts/build.js. Import this file directly into MusicFree.
var __getOwnPropNames = Object.getOwnPropertyNames;
var __commonJS = (cb, mod) => function __require() {
  return mod || (0, cb[__getOwnPropNames(cb)[0]])((mod = { exports: {} }).exports, mod), mod.exports;
};

// src/shared.js
var require_shared = __commonJS({
  "src/shared.js"(exports2, module2) {
    var axios2 = require("axios");
    var PAGE_SIZE2 = 30;
    var UA2 = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36";
    function text2(value, fallback) {
      if (value === void 0 || value === null || value === "") return fallback || "";
      return String(value);
    }
    function stripHtml2(value) {
      return text2(value).replace(/<[^>]*>/g, "").replace(/&amp;/g, "&").replace(/&lt;/g, "<").replace(/&gt;/g, ">").replace(/&quot;/g, '"').replace(/&#39;/g, "'").trim();
    }
    function toHttps2(value, size) {
      return text2(value).replace(/^http:\/\//i, "https://").replace(/\{size\}/g, text2(size, "400"));
    }
    function parseJsonp(value) {
      const raw = text2(value).trim();
      const start = raw.indexOf("(");
      const end = raw.lastIndexOf(")");
      return JSON.parse(start >= 0 && end > start ? raw.slice(start + 1, end) : raw);
    }
    function parseDuration2(value) {
      if (typeof value === "number") {
        return value > 1e5 ? Math.floor(value / 1e3) : Math.floor(value);
      }
      const raw = text2(value);
      if (/^\d+:\d{1,2}$/.test(raw)) {
        const parts = raw.split(":").map(Number);
        return parts[0] * 60 + parts[1];
      }
      const parsed = Number(raw);
      return Number.isFinite(parsed) ? Math.floor(parsed) : void 0;
    }
    function artistNames(list, separator) {
      if (!Array.isArray(list)) return text2(list, "\u672A\u77E5\u6B4C\u624B");
      return list.map(function(artist) {
        return text2(artist && (artist.name || artist.title || artist.author_name));
      }).filter(Boolean).join(separator || "\u3001");
    }
    function formatLrcTime2(seconds) {
      const value = Number(seconds) || 0;
      const minutes = Math.floor(value / 60);
      const rest = (value - minutes * 60).toFixed(2).padStart(5, "0");
      return "[" + String(minutes).padStart(2, "0") + ":" + rest + "]";
    }
    function decodeBase64(value) {
      if (!value) return "";
      try {
        return Buffer.from(value, "base64").toString("utf8");
      } catch (error) {
        return text2(value);
      }
    }
    function userVariables() {
      try {
        return env.getUserVariables() || {};
      } catch (error) {
        return {};
      }
    }
    function qualityLevel(quality) {
      return {
        low: "standard",
        standard: "standard",
        high: "exhigh",
        super: "lossless"
      }[quality] || "standard";
    }
    async function resolveMedia2(source, musicItem, quality) {
      const rid = text2(musicItem.sourceRid || musicItem.rid || musicItem.id);
      const response = await axios2.post(
        "https://musicserver.haitangw.cc/v1/music/resolve-url",
        { source, rid, level: qualityLevel(quality) },
        {
          headers: { "Content-Type": "application/json", Accept: "application/json" },
          timeout: 9e3
        }
      );
      const data = response.data && response.data.data;
      if (!data || !data.url) throw new Error("\u64AD\u653E\u5730\u5740\u89E3\u6790\u5931\u8D25");
      return { url: data.url, headers: data.playbackHeaders || data.headers || void 0 };
    }
    function normalizeComment(item) {
      const rawTime = Number(item.time);
      return {
        id: text2(item.id),
        nickName: text2(item.userName, "\u533F\u540D\u7528\u6237"),
        comment: text2(item.text),
        avatar: text2(item.avatar),
        like: Number(item.likedCount) || 0,
        createAt: Number.isFinite(rawTime) ? rawTime < 1e11 ? rawTime * 1e3 : rawTime : void 0,
        location: text2(item.location),
        replies: Array.isArray(item.reply) ? item.reply.map(function(reply) {
          const normalized = normalizeComment(reply);
          delete normalized.replies;
          return normalized;
        }) : []
      };
    }
    async function getComments2(source, musicItem, page) {
      const currentPage = Math.max(1, Number(page) || 1);
      const rid = text2(musicItem.sourceRid || musicItem.rid || musicItem.id);
      const response = await axios2.get(
        "https://music.haitangw.cc/pinglun/" + source + "pl.php",
        {
          params: { songmid: rid, type: "hot", page: currentPage, limit: 20 },
          headers: { "User-Agent": UA2 },
          timeout: 8e3
        }
      );
      const root = response.data || {};
      if (Number(root.code) !== 200) throw new Error(root.message || "\u8BC4\u8BBA\u52A0\u8F7D\u5931\u8D25");
      const data = root.data || {};
      const comments = Array.isArray(data.comments) ? data.comments : [];
      return {
        isEnd: currentPage >= Number(data.maxPage || 1) || comments.length < 20,
        data: comments.map(normalizeComment)
      };
    }
    function extractNumericId2(value) {
      const matches = text2(value).match(/\d+/g);
      if (!matches || !matches.length) throw new Error("\u65E0\u6CD5\u8BC6\u522B ID");
      return matches[matches.length - 1];
    }
    module2.exports = {
      axios: axios2,
      PAGE_SIZE: PAGE_SIZE2,
      UA: UA2,
      text: text2,
      stripHtml: stripHtml2,
      toHttps: toHttps2,
      parseJsonp,
      parseDuration: parseDuration2,
      artistNames,
      formatLrcTime: formatLrcTime2,
      decodeBase64,
      userVariables,
      resolveMedia: resolveMedia2,
      getComments: getComments2,
      extractNumericId: extractNumericId2
    };
  }
});

// src/kuwo.js
var {
  axios,
  PAGE_SIZE,
  UA,
  text,
  stripHtml,
  toHttps,
  parseDuration,
  formatLrcTime,
  resolveMedia,
  getComments,
  extractNumericId
} = require_shared();
var KUWO_PC_PRODUCT = "kwplayer_pc_9.0.5.0";
var KUWO_APP_UID = "76039576";
var UNSUPPORTED_RECOMMEND_TAG_IDS = /* @__PURE__ */ new Set(["18", "20", "241"]);
var recommendTagCache;
var recommendTagCacheAt = 0;
async function getKuwoRecommendTagGroups() {
  const now = Date.now();
  if (recommendTagCache && now - recommendTagCacheAt < 5 * 60 * 1e3) {
    return recommendTagCache;
  }
  const response = await axios.get(
    "https://wapi.kuwo.cn/api/pc/classify/playlist/getTagList",
    {
      params: {
        cmd: "rcm_keyword_playlist",
        user: 0,
        prod: KUWO_PC_PRODUCT,
        vipver: KUWO_PC_PRODUCT,
        source: KUWO_PC_PRODUCT,
        loginUid: 0,
        loginSid: 0,
        appUid: KUWO_APP_UID
      },
      headers: { "User-Agent": UA },
      timeout: 8e3
    }
  );
  const groups = response.data && response.data.data;
  if (!Array.isArray(groups) || !groups.some(function(group) {
    return Array.isArray(group.data) && group.data.length > 0;
  })) {
    throw new Error("\u9177\u6211\u5B98\u65B9\u6B4C\u5355\u5206\u7C7B\u4E3A\u7A7A");
  }
  recommendTagCache = groups;
  recommendTagCacheAt = now;
  return groups;
}
function mapRecommendSheet(item) {
  return {
    id: text(item.id),
    title: text(item.name),
    artist: text(item.uname),
    artwork: toHttps(item.pc_new_focus || item.img),
    description: text(item.desc || item.info),
    worksNum: Number(item.total) || void 0,
    playCount: Number(item.listencnt) || void 0
  };
}
function artwork(item) {
  const path = text(item.web_albumpic_short || item.WEB_ALBUMPIC_SHORT);
  if (!path) return toHttps(item.pic || item.PIC || item.albumpic);
  if (/^https?:\/\//i.test(path)) return toHttps(path);
  return "https://img1.kuwo.cn/star/albumcover/300/" + path.replace(/^\//, "");
}
function mapMusic(item) {
  const rid = text(
    item.rid || item.DC_TARGETID || item.musicrid || item.MUSICRID || item.id
  ).replace(
    /^MUSIC_/,
    ""
  );
  return {
    id: rid,
    title: stripHtml(item.name || item.songname || item.SONGNAME),
    artist: stripHtml(item.artist || item.ARTIST || "\u672A\u77E5\u6B4C\u624B"),
    album: stripHtml(item.album || item.ALBUM),
    duration: parseDuration(item.duration || item.DURATION),
    artwork: artwork(item),
    sourceRid: rid
  };
}
async function getTopLists() {
  const response = await axios.get("https://wapi.kuwo.cn/api/pc/bang/list", {
    headers: { "User-Agent": UA, Referer: "https://www.kuwo.cn/rankList" },
    timeout: 8e3
  });
  const root = response.data && response.data.data || response.data || {};
  return (root.child || []).map(function(group) {
    return {
      title: text(group.disname || group.name),
      data: (group.child || []).map(function(item) {
        const coverImg = toHttps(item.pic5 || item.pic2 || item.pic);
        return {
          id: text(item.sourceid || item.id),
          bangId: text(item.sourceid || item.id),
          title: text(item.disname || item.name),
          description: text(item.intro || item.tips),
          coverImg,
          artwork: coverImg,
          updateTime: text(item.pubTime)
        };
      })
    };
  });
}
async function search(query, page, type) {
  if (type !== "music") return { isEnd: true, data: [] };
  const currentPage = Math.max(1, Number(page) || 1);
  const response = await axios.get("http://search.kuwo.cn/r.s", {
    params: {
      client: "kt",
      all: query,
      pn: currentPage - 1,
      rn: PAGE_SIZE,
      uid: "794762570",
      ver: "kwplayer_ar_9.2.2.1",
      ft: "music",
      cluster: 0,
      strategy: 2012,
      encoding: "utf8",
      rformat: "json",
      mobi: 1
    },
    headers: { "User-Agent": UA },
    timeout: 8e3
  });
  const root = response.data || {};
  const list = root.abslist || root.data && root.data.list || [];
  return { isEnd: list.length < PAGE_SIZE, data: list.map(mapMusic) };
}
async function getLyric(musicItem) {
  const rid = text(musicItem.sourceRid || musicItem.id);
  const response = await axios.get("https://wapi.kuwo.cn/openapi/v1/www/lyric/getlyric", {
    params: { musicId: rid, httpsStatus: 1 },
    headers: { "User-Agent": UA, Referer: "https://www.kuwo.cn/" },
    timeout: 8e3
  });
  const list = response.data && response.data.data && response.data.data.lrclist || response.data && response.data.lrclist || [];
  return {
    rawLrc: list.map(function(line) {
      return formatLrcTime(line.time) + text(line.lineLyric || line.line);
    }).join("\n")
  };
}
async function getMusicInfo(musicItem) {
  const rid = text(musicItem.sourceRid || musicItem.id);
  const response = await axios.get("http://musicpay.kuwo.cn/music.pay", {
    params: { op: "query", action: "play", ids: rid },
    headers: { "User-Agent": UA },
    timeout: 8e3
  });
  const item = response.data && response.data.songs && response.data.songs[0];
  if (!item) return {};
  return {
    title: text(item.name),
    artist: text(item.artist),
    album: text(item.album),
    artwork: text(item.musicPic || item.albumPic),
    duration: parseDuration(item.duration),
    sourceRid: rid
  };
}
async function getTopListDetail(topListItem, page) {
  const currentPage = Math.max(1, Number(page) || 1);
  const response = await axios.get("https://wapi.kuwo.cn/api/www/bang/bang/musicList", {
    params: { bangId: topListItem.bangId || topListItem.id, pn: currentPage, rn: PAGE_SIZE },
    headers: { "User-Agent": UA, Referer: "https://www.kuwo.cn/" },
    timeout: 8e3
  });
  const root = response.data && response.data.data || {};
  const list = root.musicList || [];
  const result = { isEnd: list.length < PAGE_SIZE, musicList: list.map(mapMusic) };
  if (currentPage === 1) {
    const coverImg = text(topListItem.coverImg || topListItem.artwork) || text(root.img);
    result.topListItem = { coverImg, artwork: coverImg };
  }
  return result;
}
async function getRecommendSheetsByTag(tag, page) {
  const currentPage = Math.max(1, Number(page) || 1);
  const tagId = text(tag && tag.id);
  const digest = text(tag && tag.digest);
  const isRecommend = !tagId || tagId === "__recommend__";
  if (!isRecommend && digest === "43") {
    const response2 = await axios.get("https://mobileinterfaces.kuwo.cn/er.s", {
      params: { type: "get_pc_qz_data", f: "web", id: tagId, prod: "pc" },
      headers: { "User-Agent": UA },
      timeout: 8e3
    });
    const groups = Array.isArray(response2.data) ? response2.data : [];
    const seen = /* @__PURE__ */ new Set();
    const allSheets = [];
    groups.forEach(function(group) {
      if (/^分类/.test(text(group.label))) return;
      const list2 = Array.isArray(group.list) ? group.list : [];
      list2.forEach(function(item) {
        const id = text(item.id);
        if (!id || seen.has(id) || item.type && item.type !== "songlist") return;
        seen.add(id);
        allSheets.push(item);
      });
    });
    const start = (currentPage - 1) * 20;
    const pageSheets = allSheets.slice(start, start + 20);
    return {
      isEnd: start + pageSheets.length >= allSheets.length,
      data: pageSheets.map(mapRecommendSheet)
    };
  }
  const endpoint = isRecommend ? "https://wapi.kuwo.cn/api/pc/classify/playlist/getRcmPlayList" : "https://wapi.kuwo.cn/api/pc/classify/playlist/getTagPlayList";
  const params = {
    loginUid: 0,
    loginSid: 0,
    appUid: KUWO_APP_UID,
    pn: currentPage - 1,
    rn: 20
  };
  if (isRecommend) params.order = "hot";
  else params.id = tagId;
  const response = await axios.get(endpoint, {
    params,
    headers: { "User-Agent": UA },
    timeout: 8e3
  });
  const data = response.data && response.data.data || {};
  const list = data.data || [];
  return {
    isEnd: currentPage * 20 >= Number(data.total || 0) || list.length < 20,
    data: list.map(mapRecommendSheet)
  };
}
async function getMusicSheetInfo(sheetItem, page) {
  const currentPage = Math.max(1, Number(page) || 1);
  const pageSize = 30;
  const response = await axios.get("http://nplserver.kuwo.cn/pl.svc", {
    params: {
      op: "getlistinfo",
      pid: sheetItem.id,
      pn: currentPage - 1,
      rn: pageSize,
      encode: "utf8",
      keyset: "pl2012",
      vipver: "MUSIC_9.1.1.2_BCS2",
      newver: 1
    },
    headers: { "User-Agent": UA },
    timeout: 9e3
  });
  const data = response.data || {};
  const musicList = data.musiclist || data.musicList || [];
  const result = {
    isEnd: currentPage * pageSize >= Number(data.total || 0) || musicList.length < pageSize,
    musicList: musicList.map(mapMusic)
  };
  if (currentPage === 1) {
    result.sheetItem = {
      title: text(data.title || sheetItem.title),
      artist: text(data.uname),
      artwork: toHttps(data.pic),
      description: text(data.info),
      worksNum: Number(data.total) || musicList.length,
      playCount: Number(data.playnum) || void 0
    };
  }
  return result;
}
async function getRecommendSheetTags() {
  const groups = await getKuwoRecommendTagGroups();
  return {
    pinned: [{ id: "__recommend__", title: "\u7CBE\u9009\u6B4C\u5355" }],
    data: groups.filter(function(group) {
      return Array.isArray(group.data) && group.data.length > 0;
    }).map(function(group) {
      return {
        title: text(group.name),
        data: group.data.filter(function(item) {
          return !UNSUPPORTED_RECOMMEND_TAG_IDS.has(text(item.id));
        }).map(function(item) {
          return {
            id: text(item.id),
            title: text(item.name),
            digest: text(item.digest)
          };
        })
      };
    }).filter(function(group) {
      return group.data.length > 0;
    })
  };
}
async function importMusicSheet(urlLike) {
  const id = extractNumericId(urlLike);
  return (await getMusicSheetInfo({ id, title: "\u5BFC\u5165\u6B4C\u5355" }, 1)).musicList;
}
module.exports = {
  platform: "\u9177\u6211\u97F3\u4E50",
  version: "1.3.4",
  srcUrl: "https://droidzf.github.io/musicfree/kuwo.js",
  author: "zero",
  description: "\u72EC\u7ACB\u9177\u6211\u97F3\u4E50\u63D2\u4EF6\uFF1A\u641C\u7D22\u3001\u64AD\u653E\u3001\u6B4C\u8BCD\u3001\u699C\u5355\u3001\u63A8\u8350\u6B4C\u5355\u3001\u6B4C\u5355\u8BE6\u60C5\u548C\u8BC4\u8BBA\u3002",
  cacheControl: "no-store",
  supportedSearchType: ["music"],
  hints: { importMusicSheet: ["\u652F\u6301\u9177\u6211\u6B4C\u5355\u94FE\u63A5\u6216\u7EAF\u6570\u5B57\u6B4C\u5355 ID\u3002"] },
  search,
  getMediaSource: function(musicItem, quality) {
    return resolveMedia("kw", musicItem, quality);
  },
  getLyric,
  getMusicInfo,
  getTopLists,
  getTopListDetail,
  getRecommendSheetTags,
  getRecommendSheetsByTag,
  getMusicSheetInfo,
  importMusicSheet,
  getMusicComments: function(musicItem, page) {
    return getComments("kw", musicItem, page);
  }
};
