// Generated by scripts/build.js. Import this file directly into MusicFree.
var __getOwnPropNames = Object.getOwnPropertyNames;
var __commonJS = (cb, mod) => function __require() {
  return mod || (0, cb[__getOwnPropNames(cb)[0]])((mod = { exports: {} }).exports, mod), mod.exports;
};

// src/shared.js
var require_shared = __commonJS({
  "src/shared.js"(exports2, module2) {
    var axios2 = require("axios");
    var PAGE_SIZE2 = 30;
    var UA2 = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36";
    function text2(value, fallback) {
      if (value === void 0 || value === null || value === "") return fallback || "";
      return String(value);
    }
    function stripHtml2(value) {
      return text2(value).replace(/<[^>]*>/g, "").replace(/&amp;/g, "&").replace(/&lt;/g, "<").replace(/&gt;/g, ">").replace(/&quot;/g, '"').replace(/&#39;/g, "'").trim();
    }
    function parseDuration2(value) {
      if (typeof value === "number") {
        return value > 1e5 ? Math.floor(value / 1e3) : Math.floor(value);
      }
      const raw = text2(value);
      if (/^\d+:\d{1,2}$/.test(raw)) {
        const parts = raw.split(":").map(Number);
        return parts[0] * 60 + parts[1];
      }
      const parsed = Number(raw);
      return Number.isFinite(parsed) ? Math.floor(parsed) : void 0;
    }
    function artistNames(list, separator) {
      if (!Array.isArray(list)) return text2(list, "\u672A\u77E5\u6B4C\u624B");
      return list.map(function(artist) {
        return text2(artist && (artist.name || artist.title || artist.author_name));
      }).filter(Boolean).join(separator || "\u3001");
    }
    function formatLrcTime2(seconds) {
      const value = Number(seconds) || 0;
      const minutes = Math.floor(value / 60);
      const rest = (value - minutes * 60).toFixed(2).padStart(5, "0");
      return "[" + String(minutes).padStart(2, "0") + ":" + rest + "]";
    }
    function decodeBase64(value) {
      if (!value) return "";
      try {
        return Buffer.from(value, "base64").toString("utf8");
      } catch (error) {
        return text2(value);
      }
    }
    function userVariables() {
      try {
        return env.getUserVariables() || {};
      } catch (error) {
        return {};
      }
    }
    function qualityLevel(quality) {
      return {
        low: "standard",
        standard: "standard",
        high: "exhigh",
        super: "lossless"
      }[quality] || "standard";
    }
    async function resolveMedia2(source, musicItem, quality) {
      const rid = text2(musicItem.sourceRid || musicItem.rid || musicItem.id);
      const response = await axios2.post(
        "https://musicserver.haitangw.cc/v1/music/resolve-url",
        { source, rid, level: qualityLevel(quality) },
        {
          headers: { "Content-Type": "application/json", Accept: "application/json" },
          timeout: 9e3
        }
      );
      const data = response.data && response.data.data;
      if (!data || !data.url) throw new Error("\u64AD\u653E\u5730\u5740\u89E3\u6790\u5931\u8D25");
      return { url: data.url, headers: data.playbackHeaders || data.headers || void 0 };
    }
    function normalizeComment(item) {
      const rawTime = Number(item.time);
      return {
        id: text2(item.id),
        nickName: text2(item.userName, "\u533F\u540D\u7528\u6237"),
        comment: text2(item.text),
        avatar: text2(item.avatar),
        like: Number(item.likedCount) || 0,
        createAt: Number.isFinite(rawTime) ? rawTime < 1e11 ? rawTime * 1e3 : rawTime : void 0,
        location: text2(item.location),
        replies: Array.isArray(item.reply) ? item.reply.map(function(reply) {
          const normalized = normalizeComment(reply);
          delete normalized.replies;
          return normalized;
        }) : []
      };
    }
    async function getComments2(source, musicItem, page) {
      const currentPage = Math.max(1, Number(page) || 1);
      const rid = text2(musicItem.sourceRid || musicItem.rid || musicItem.id);
      const response = await axios2.get(
        "https://music.haitangw.cc/pinglun/" + source + "pl.php",
        {
          params: { songmid: rid, type: "hot", page: currentPage, limit: 20 },
          headers: { "User-Agent": UA2 },
          timeout: 8e3
        }
      );
      const root = response.data || {};
      if (Number(root.code) !== 200) throw new Error(root.message || "\u8BC4\u8BBA\u52A0\u8F7D\u5931\u8D25");
      const data = root.data || {};
      const comments = Array.isArray(data.comments) ? data.comments : [];
      return {
        isEnd: currentPage >= Number(data.maxPage || 1) || comments.length < 20,
        data: comments.map(normalizeComment)
      };
    }
    function extractNumericId2(value) {
      const matches = text2(value).match(/\d+/g);
      if (!matches || !matches.length) throw new Error("\u65E0\u6CD5\u8BC6\u522B ID");
      return matches[matches.length - 1];
    }
    function createTopListGroups2(platformKey, groups) {
      return groups.map(function(group) {
        return {
          title: group.title,
          data: group.data.map(function(item) {
            return {
              id: text2(item[0]),
              bangId: text2(item[0]),
              title: item[1],
              description: item[2],
              artwork: "https://droidzf.github.io/musicfree/covers/" + platformKey + "-" + text2(item[0]) + ".png"
            };
          })
        };
      });
    }
    module2.exports = {
      axios: axios2,
      PAGE_SIZE: PAGE_SIZE2,
      UA: UA2,
      text: text2,
      stripHtml: stripHtml2,
      parseDuration: parseDuration2,
      artistNames,
      formatLrcTime: formatLrcTime2,
      decodeBase64,
      userVariables,
      resolveMedia: resolveMedia2,
      getComments: getComments2,
      extractNumericId: extractNumericId2,
      createTopListGroups: createTopListGroups2
    };
  }
});

// src/kuwo.js
var {
  axios,
  PAGE_SIZE,
  UA,
  text,
  stripHtml,
  parseDuration,
  formatLrcTime,
  resolveMedia,
  getComments,
  extractNumericId,
  createTopListGroups
} = require_shared();
var TOP_LIST_GROUPS = [
  {
    title: "\u5DC5\u5CF0\u699C",
    data: [
      ["93", "\u98D9\u5347\u699C", "\u805A\u5408\u8FD1\u671F\u70ED\u5EA6\u5FEB\u901F\u4E0A\u5347\u7684\u6B4C\u66F2\u3002"],
      ["17", "\u65B0\u6B4C\u699C", "\u6536\u5F55\u8FD1\u671F\u53D1\u5E03\u5E76\u53D7\u5230\u5173\u6CE8\u7684\u65B0\u6B4C\u3002"],
      ["16", "\u70ED\u6B4C\u699C", "\u5448\u73B0\u9177\u6211\u97F3\u4E50\u5F53\u524D\u7EFC\u5408\u70ED\u5EA6\u8F83\u9AD8\u7684\u6B4C\u66F2\u3002"]
    ]
  },
  {
    title: "\u7279\u8272\u699C",
    data: [
      ["158", "\u6296\u97F3\u699C", "\u6536\u5F55\u77ED\u89C6\u9891\u5E73\u53F0\u8FD1\u671F\u70ED\u95E8\u97F3\u4E50\u3002"],
      ["176", "\u4E07\u7269\u699C", "\u5C55\u793A\u8DE8\u573A\u666F\u3001\u8DE8\u98CE\u683C\u7684\u70ED\u95E8\u97F3\u4E50\u3002"],
      ["145", "\u7545\u542C\u699C", "\u805A\u5408\u8FD1\u671F\u7528\u6237\u6301\u7EED\u6536\u542C\u7684\u70ED\u95E8\u6B4C\u66F2\u3002"]
    ]
  }
];
var SHEET_TAGS = [
  ["2189", "\u6296\u97F3"],
  ["1265", "\u7ECF\u5178"],
  ["2200", "\u60C5\u6B4C"],
  ["2199", "BGM"],
  ["2212", "\u6F14\u5531\u4F1A"],
  ["1877", "\u6E38\u620F"],
  ["155", "\u6000\u65E7"],
  ["621", "\u7F51\u7EDC"],
  ["2201", "\u5408\u5531"],
  ["181", "ACG"],
  ["171", "\u513F\u7AE5"]
];
function artwork(item) {
  const path = text(item.web_albumpic_short || item.WEB_ALBUMPIC_SHORT);
  if (!path) return text(item.pic || item.PIC || item.albumpic);
  if (/^https?:\/\//i.test(path)) return path;
  return "https://img1.kuwo.cn/star/albumcover/300/" + path.replace(/^\//, "");
}
function mapMusic(item) {
  const rid = text(item.rid || item.DC_TARGETID || item.musicrid || item.MUSICRID).replace(
    /^MUSIC_/,
    ""
  );
  return {
    id: rid,
    title: stripHtml(item.name || item.songname || item.SONGNAME),
    artist: stripHtml(item.artist || item.ARTIST || "\u672A\u77E5\u6B4C\u624B"),
    album: stripHtml(item.album || item.ALBUM),
    duration: parseDuration(item.duration || item.DURATION),
    artwork: artwork(item),
    sourceRid: rid
  };
}
async function search(query, page, type) {
  if (type !== "music") return { isEnd: true, data: [] };
  const currentPage = Math.max(1, Number(page) || 1);
  const response = await axios.get("http://search.kuwo.cn/r.s", {
    params: {
      client: "kt",
      all: query,
      pn: currentPage - 1,
      rn: PAGE_SIZE,
      uid: "794762570",
      ver: "kwplayer_ar_9.2.2.1",
      ft: "music",
      cluster: 0,
      strategy: 2012,
      encoding: "utf8",
      rformat: "json",
      mobi: 1
    },
    headers: { "User-Agent": UA },
    timeout: 8e3
  });
  const root = response.data || {};
  const list = root.abslist || root.data && root.data.list || [];
  return { isEnd: list.length < PAGE_SIZE, data: list.map(mapMusic) };
}
async function getLyric(musicItem) {
  const rid = text(musicItem.sourceRid || musicItem.id);
  const response = await axios.get("https://wapi.kuwo.cn/openapi/v1/www/lyric/getlyric", {
    params: { musicId: rid, httpsStatus: 1 },
    headers: { "User-Agent": UA, Referer: "https://www.kuwo.cn/" },
    timeout: 8e3
  });
  const list = response.data && response.data.data && response.data.data.lrclist || response.data && response.data.lrclist || [];
  return {
    rawLrc: list.map(function(line) {
      return formatLrcTime(line.time) + text(line.lineLyric || line.line);
    }).join("\n")
  };
}
async function getMusicInfo(musicItem) {
  const rid = text(musicItem.sourceRid || musicItem.id);
  const response = await axios.get("http://musicpay.kuwo.cn/music.pay", {
    params: { op: "query", action: "play", ids: rid },
    headers: { "User-Agent": UA },
    timeout: 8e3
  });
  const item = response.data && response.data.songs && response.data.songs[0];
  if (!item) return {};
  return {
    title: text(item.name),
    artist: text(item.artist),
    album: text(item.album),
    artwork: text(item.musicPic || item.albumPic),
    duration: parseDuration(item.duration),
    sourceRid: rid
  };
}
async function getTopListDetail(topListItem, page) {
  const currentPage = Math.max(1, Number(page) || 1);
  const response = await axios.get("https://wapi.kuwo.cn/api/www/bang/bang/musicList", {
    params: { bangId: topListItem.bangId || topListItem.id, pn: currentPage, rn: PAGE_SIZE },
    headers: { "User-Agent": UA, Referer: "https://www.kuwo.cn/" },
    timeout: 8e3
  });
  const root = response.data && response.data.data || {};
  const list = root.musicList || [];
  const result = { isEnd: list.length < PAGE_SIZE, musicList: list.map(mapMusic) };
  if (currentPage === 1) result.topListItem = { artwork: text(root.img) };
  return result;
}
async function getRecommendSheetsByTag(tag, page) {
  const currentPage = Math.max(1, Number(page) || 1);
  const response = await axios.get("https://music.haitangw.cc/music/gedan/kw.php", {
    params: {
      type: "getTagLists",
      id: text(tag && tag.id, "2189"),
      page: currentPage,
      limit: 15,
      order: "hot"
    },
    timeout: 8e3
  });
  const root = response.data || {};
  if (Number(root.code) !== 200) throw new Error(root.msg || "\u9177\u6211\u6B4C\u5355\u52A0\u8F7D\u5931\u8D25");
  const data = root.data || {};
  const list = data.data || [];
  return {
    isEnd: currentPage * 15 >= Number(data.total || 0) || list.length < 15,
    data: list.map(function(item) {
      return {
        id: text(item.id),
        title: text(item.name),
        artist: text(item.uname),
        artwork: text(item.img),
        description: text(item.desc || item.info),
        worksNum: Number(item.total) || void 0,
        playCount: Number(item.listencnt) || void 0
      };
    })
  };
}
async function getMusicSheetInfo(sheetItem, page) {
  const currentPage = Math.max(1, Number(page) || 1);
  const response = await axios.get("https://music.haitangw.cc/music/gedan/kwlist.php", {
    params: { id: sheetItem.id, page: currentPage, limit: 500, type: "list" },
    timeout: 9e3
  });
  const root = response.data || {};
  if (Number(root.code) !== 200) throw new Error(root.msg || "\u9177\u6211\u6B4C\u5355\u8BE6\u60C5\u52A0\u8F7D\u5931\u8D25");
  const data = root.data || {};
  const result = { isEnd: true, musicList: (data.musicList || []).map(mapMusic) };
  if (currentPage === 1) {
    result.sheetItem = {
      title: text(data.name || sheetItem.title),
      artist: text(data.userName),
      artwork: text(data.img),
      worksNum: Number(data.total) || result.musicList.length
    };
  }
  return result;
}
async function importMusicSheet(urlLike) {
  const id = extractNumericId(urlLike);
  return (await getMusicSheetInfo({ id, title: "\u5BFC\u5165\u6B4C\u5355" }, 1)).musicList;
}
module.exports = {
  platform: "\u9177\u6211\u97F3\u4E50",
  version: "1.2.0",
  srcUrl: "https://droidzf.github.io/musicfree/kuwo.js",
  author: "zero",
  description: "\u72EC\u7ACB\u9177\u6211\u97F3\u4E50\u63D2\u4EF6\uFF1A\u641C\u7D22\u3001\u64AD\u653E\u3001\u6B4C\u8BCD\u3001\u699C\u5355\u3001\u63A8\u8350\u6B4C\u5355\u3001\u6B4C\u5355\u8BE6\u60C5\u548C\u8BC4\u8BBA\u3002",
  cacheControl: "no-store",
  supportedSearchType: ["music"],
  hints: { importMusicSheet: ["\u652F\u6301\u9177\u6211\u6B4C\u5355\u94FE\u63A5\u6216\u7EAF\u6570\u5B57\u6B4C\u5355 ID\u3002"] },
  search,
  getMediaSource: function(musicItem, quality) {
    return resolveMedia("kw", musicItem, quality);
  },
  getLyric,
  getMusicInfo,
  getTopLists: function() {
    return Promise.resolve(createTopListGroups("kuwo", TOP_LIST_GROUPS));
  },
  getTopListDetail,
  getRecommendSheetTags: function() {
    return Promise.resolve({
      pinned: [{ id: "2189", title: "\u6296\u97F3" }],
      data: [
        {
          title: "\u6B4C\u5355\u5206\u7C7B",
          data: SHEET_TAGS.map(function(item) {
            return { id: item[0], title: item[1] };
          })
        }
      ]
    });
  },
  getRecommendSheetsByTag,
  getMusicSheetInfo,
  importMusicSheet,
  getMusicComments: function(musicItem, page) {
    return getComments("kw", musicItem, page);
  }
};
