// Generated by scripts/build.js. Import this file directly into MusicFree.
var __getOwnPropNames = Object.getOwnPropertyNames;
var __commonJS = (cb, mod) => function __require() {
  return mod || (0, cb[__getOwnPropNames(cb)[0]])((mod = { exports: {} }).exports, mod), mod.exports;
};

// src/shared.js
var require_shared = __commonJS({
  "src/shared.js"(exports2, module2) {
    var axios2 = require("axios");
    var PAGE_SIZE2 = 30;
    var UA2 = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36";
    function text2(value, fallback) {
      if (value === void 0 || value === null || value === "") return fallback || "";
      return String(value);
    }
    function stripHtml(value) {
      return text2(value).replace(/<[^>]*>/g, "").replace(/&amp;/g, "&").replace(/&lt;/g, "<").replace(/&gt;/g, ">").replace(/&quot;/g, '"').replace(/&#39;/g, "'").trim();
    }
    function toHttps2(value, size) {
      return text2(value).replace(/^http:\/\//i, "https://").replace(/\{size\}/g, text2(size, "400"));
    }
    function parseJsonp(value) {
      const raw = text2(value).trim();
      const start = raw.indexOf("(");
      const end = raw.lastIndexOf(")");
      return JSON.parse(start >= 0 && end > start ? raw.slice(start + 1, end) : raw);
    }
    function parseDuration2(value) {
      if (typeof value === "number") {
        return value > 1e5 ? Math.floor(value / 1e3) : Math.floor(value);
      }
      const raw = text2(value);
      if (/^\d+:\d{1,2}$/.test(raw)) {
        const parts = raw.split(":").map(Number);
        return parts[0] * 60 + parts[1];
      }
      const parsed = Number(raw);
      return Number.isFinite(parsed) ? Math.floor(parsed) : void 0;
    }
    function artistNames2(list, separator) {
      if (!Array.isArray(list)) return text2(list, "\u672A\u77E5\u6B4C\u624B");
      return list.map(function(artist) {
        return text2(artist && (artist.name || artist.title || artist.author_name));
      }).filter(Boolean).join(separator || "\u3001");
    }
    function formatLrcTime(seconds) {
      const value = Number(seconds) || 0;
      const minutes = Math.floor(value / 60);
      const rest = (value - minutes * 60).toFixed(2).padStart(5, "0");
      return "[" + String(minutes).padStart(2, "0") + ":" + rest + "]";
    }
    function decodeBase64(value) {
      if (!value) return "";
      try {
        return Buffer.from(value, "base64").toString("utf8");
      } catch (error) {
        return text2(value);
      }
    }
    function userVariables2() {
      try {
        return env.getUserVariables() || {};
      } catch (error) {
        return {};
      }
    }
    function qualityLevel(quality) {
      return {
        low: "standard",
        standard: "standard",
        high: "exhigh",
        super: "lossless"
      }[quality] || "standard";
    }
    async function resolveMedia2(source, musicItem, quality) {
      const rid = text2(musicItem.sourceRid || musicItem.rid || musicItem.id);
      const response = await axios2.post(
        "https://musicserver.haitangw.cc/v1/music/resolve-url",
        { source, rid, level: qualityLevel(quality) },
        {
          headers: { "Content-Type": "application/json", Accept: "application/json" },
          timeout: 9e3
        }
      );
      const data = response.data && response.data.data;
      if (!data || !data.url) throw new Error("\u64AD\u653E\u5730\u5740\u89E3\u6790\u5931\u8D25");
      return { url: data.url, headers: data.playbackHeaders || data.headers || void 0 };
    }
    function normalizeComment(item) {
      const rawTime = Number(item.time);
      return {
        id: text2(item.id),
        nickName: text2(item.userName, "\u533F\u540D\u7528\u6237"),
        comment: text2(item.text),
        avatar: text2(item.avatar),
        like: Number(item.likedCount) || 0,
        createAt: Number.isFinite(rawTime) ? rawTime < 1e11 ? rawTime * 1e3 : rawTime : void 0,
        location: text2(item.location),
        replies: Array.isArray(item.reply) ? item.reply.map(function(reply) {
          const normalized = normalizeComment(reply);
          delete normalized.replies;
          return normalized;
        }) : []
      };
    }
    async function getComments2(source, musicItem, page) {
      const currentPage = Math.max(1, Number(page) || 1);
      const rid = text2(musicItem.sourceRid || musicItem.rid || musicItem.id);
      const response = await axios2.get(
        "https://music.haitangw.cc/pinglun/" + source + "pl.php",
        {
          params: { songmid: rid, type: "hot", page: currentPage, limit: 20 },
          headers: { "User-Agent": UA2 },
          timeout: 8e3
        }
      );
      const root = response.data || {};
      if (Number(root.code) !== 200) throw new Error(root.message || "\u8BC4\u8BBA\u52A0\u8F7D\u5931\u8D25");
      const data = root.data || {};
      const comments = Array.isArray(data.comments) ? data.comments : [];
      return {
        isEnd: currentPage >= Number(data.maxPage || 1) || comments.length < 20,
        data: comments.map(normalizeComment)
      };
    }
    function extractNumericId2(value) {
      const matches = text2(value).match(/\d+/g);
      if (!matches || !matches.length) throw new Error("\u65E0\u6CD5\u8BC6\u522B ID");
      return matches[matches.length - 1];
    }
    module2.exports = {
      axios: axios2,
      PAGE_SIZE: PAGE_SIZE2,
      UA: UA2,
      text: text2,
      stripHtml,
      toHttps: toHttps2,
      parseJsonp,
      parseDuration: parseDuration2,
      artistNames: artistNames2,
      formatLrcTime,
      decodeBase64,
      userVariables: userVariables2,
      resolveMedia: resolveMedia2,
      getComments: getComments2,
      extractNumericId: extractNumericId2
    };
  }
});

// src/netease.js
var CryptoJS = require("crypto-js");
var cheerio = require("cheerio");
var {
  axios,
  PAGE_SIZE,
  UA,
  text,
  toHttps,
  artistNames,
  parseDuration,
  userVariables,
  resolveMedia,
  getComments,
  extractNumericId
} = require_shared();
function mapMusic(item) {
  const rid = text(item.id);
  const album = item.al || item.album || {};
  return {
    id: rid,
    title: text(item.name),
    artist: artistNames(item.ar || item.artists),
    album: text(album.name),
    duration: parseDuration(item.dt || item.duration),
    artwork: toHttps(album.picUrl),
    sourceRid: rid
  };
}
function parsePlayCount(value) {
  const raw = text(value).trim();
  const number = Number(raw.replace(/[^\d.]/g, "")) || 0;
  if (raw.indexOf("\u4EBF") >= 0) return Math.round(number * 1e8);
  if (raw.indexOf("\u4E07") >= 0) return Math.round(number * 1e4);
  return number || void 0;
}
async function getOfficialHtml(url, params) {
  const response = await axios.get(url, {
    params,
    headers: { "User-Agent": UA, Referer: "https://music.163.com/" },
    responseType: "text",
    timeout: 9e3
  });
  return text(response.data);
}
async function getTopLists() {
  const $ = cheerio.load(await getOfficialHtml("https://music.163.com/discover/toplist"));
  const groups = [];
  $(".n-minelst h2").each(function(_, heading) {
    const group = { title: $(heading).text().trim(), data: [] };
    $(heading).next("ul").find("li[data-res-id]").each(function(_2, element) {
      const item = $(element);
      const id = text(item.attr("data-res-id"));
      const coverImg = toHttps(item.find("img").attr("src")).replace(
        /\?param=\d+y\d+$/,
        "?param=300y300"
      );
      group.data.push({
        id,
        bangId: id,
        title: item.find(".name a").text().trim(),
        description: item.find(".s-fc4").text().trim(),
        coverImg,
        artwork: coverImg
      });
    });
    if (group.data.length) groups.push(group);
  });
  return groups;
}
function encryptEapi(path, payload) {
  const key = text(userVariables().neteaseEapiKey).trim();
  if (!key) {
    throw new Error("\u8BF7\u5148\u5728\u63D2\u4EF6\u8BBE\u7F6E\u4E2D\u586B\u5199\u7F51\u6613\u4E91 EAPI AES Key\uFF1B\u9879\u76EE\u4E0D\u4F1A\u5185\u7F6E APK \u63D0\u53D6\u5BC6\u94A5\u3002");
  }
  const json = JSON.stringify(payload);
  const digest = CryptoJS.MD5("nobody" + path + "use" + json + "md5forencrypt").toString();
  const message = path + "-36cd479b6b5-" + json + "-36cd479b6b5-" + digest;
  const encrypted = CryptoJS.AES.encrypt(
    CryptoJS.enc.Utf8.parse(message),
    CryptoJS.enc.Utf8.parse(key),
    { mode: CryptoJS.mode.ECB, padding: CryptoJS.pad.Pkcs7 }
  );
  return encrypted.ciphertext.toString(CryptoJS.enc.Hex).toUpperCase();
}
async function search(query, page, type) {
  if (type !== "music") return { isEnd: true, data: [] };
  const currentPage = Math.max(1, Number(page) || 1);
  const apiPath = "/api/cloudsearch/pc";
  const payload = {
    s: query,
    type: 1,
    limit: PAGE_SIZE,
    offset: (currentPage - 1) * PAGE_SIZE,
    total: true
  };
  const response = await axios.post(
    "http://interface.music.163.com/eapi/batch",
    "params=" + encodeURIComponent(encryptEapi(apiPath, payload)),
    {
      headers: { "Content-Type": "application/x-www-form-urlencoded", "User-Agent": UA },
      timeout: 8e3
    }
  );
  const root = response.data || {};
  const result = root.result || root[apiPath] || root.data || {};
  const list = result.songs || result.result && result.result.songs || [];
  return {
    isEnd: currentPage * PAGE_SIZE >= Number(result.songCount || result.total || 0) || list.length < PAGE_SIZE,
    data: list.map(mapMusic)
  };
}
async function getLyric(musicItem) {
  const rid = text(musicItem.sourceRid || musicItem.id);
  const response = await axios.get("http://interface3.music.163.com/api/song/lyric", {
    params: { id: rid, os: "Linux", lv: -1, kv: -1, tv: -1 },
    headers: { "User-Agent": UA },
    timeout: 8e3
  });
  return {
    rawLrc: text(response.data && response.data.lrc && response.data.lrc.lyric),
    translation: text(response.data && response.data.tlyric && response.data.tlyric.lyric)
  };
}
async function fetchPlaylist(id) {
  const response = await axios.get("https://music.163.com/api/v6/playlist/detail", {
    params: { s: 0, id, n: 1e3, t: 0 },
    headers: { "User-Agent": UA, Referer: "https://music.163.com/" },
    timeout: 9e3
  });
  return response.data && response.data.playlist || {};
}
async function fetchSongs(ids) {
  if (!ids.length) return [];
  const response = await axios.get("https://music.163.com/api/song/detail", {
    params: { ids: JSON.stringify(ids.map(Number)) },
    headers: { "User-Agent": UA, Referer: "https://music.163.com/" },
    timeout: 9e3
  });
  return response.data && response.data.songs || [];
}
async function playlistPage(sheetItem, page, resultKey) {
  const currentPage = Math.max(1, Number(page) || 1);
  const playlist = await fetchPlaylist(sheetItem.id);
  const pageSize = 100;
  const ids = (playlist.trackIds || []).map(function(item) {
    return item.id;
  });
  const slice = ids.slice((currentPage - 1) * pageSize, currentPage * pageSize);
  let tracks = (playlist.tracks || []).filter(function(item) {
    return slice.indexOf(item.id) >= 0;
  });
  if (tracks.length < slice.length) tracks = await fetchSongs(slice);
  const result = {
    isEnd: currentPage * pageSize >= ids.length,
    musicList: tracks.map(mapMusic)
  };
  if (currentPage === 1) {
    const coverImg = toHttps(sheetItem.coverImg || sheetItem.artwork) || toHttps(playlist.coverImgUrl);
    result[resultKey] = {
      title: text(playlist.name || sheetItem.title),
      coverImg,
      artwork: coverImg,
      description: text(playlist.description),
      worksNum: Number(playlist.trackCount) || ids.length,
      playCount: Number(playlist.playCount) || void 0,
      artist: text(playlist.creator && playlist.creator.nickname)
    };
  }
  return result;
}
async function getRecommendSheetsByTag(tag, page) {
  const currentPage = Math.max(1, Number(page) || 1);
  const category = text(tag && (tag.id || tag.title), "\u5168\u90E8");
  const pageSize = 35;
  const $ = cheerio.load(
    await getOfficialHtml("https://music.163.com/discover/playlist/", {
      order: "hot",
      cat: category,
      limit: pageSize,
      offset: (currentPage - 1) * pageSize
    })
  );
  const list = [];
  $("#m-pl-container > li").each(function(_, element) {
    const item = $(element);
    const link = item.find("a.msk").first();
    const match = text(link.attr("href")).match(/[?&]id=(\d+)/);
    if (!match) return;
    list.push({
      id: match[1],
      title: text(link.attr("title") || item.find("a.tit").text()),
      artist: item.find("a.nm").first().text().trim(),
      artwork: toHttps(item.find(".u-cover img").attr("src")).replace(
        /\?param=\d+y\d+$/,
        "?param=300y300"
      ),
      playCount: parsePlayCount(item.find(".nb").text())
    });
  });
  return {
    isEnd: $("a.zbtn.znxt").length === 0,
    data: list
  };
}
async function getRecommendSheetTags() {
  const $ = cheerio.load(
    await getOfficialHtml("https://music.163.com/discover/playlist/", {
      order: "hot",
      cat: "\u5168\u90E8"
    })
  );
  const groups = [];
  $("#cateListBox dl").each(function(_, element) {
    const group = { title: $(element).find("dt").text().trim(), data: [] };
    $(element).find("dd a[data-cat]").each(function(_2, link) {
      const title = text($(link).attr("data-cat") || $(link).text());
      group.data.push({ id: title, title });
    });
    if (group.data.length) groups.push(group);
  });
  return { pinned: [{ id: "\u5168\u90E8", title: "\u5168\u90E8" }], data: groups };
}
async function getMusicInfo(musicItem) {
  const rid = text(musicItem.sourceRid || musicItem.id);
  const response = await axios.get("http://interface3.music.163.com/api/v3/song/detail", {
    params: { c: JSON.stringify([{ id: Number(rid) }]) },
    headers: { "User-Agent": UA },
    timeout: 8e3
  });
  const item = response.data && response.data.songs && response.data.songs[0];
  return item ? mapMusic(item) : {};
}
async function importMusicSheet(urlLike) {
  const id = extractNumericId(urlLike);
  const playlist = await fetchPlaylist(id);
  const ids = (playlist.trackIds || []).map(function(item) {
    return item.id;
  });
  const all = [];
  for (let index = 0; index < ids.length; index += 200) {
    const songs = await fetchSongs(ids.slice(index, index + 200));
    all.push.apply(all, songs.map(mapMusic));
  }
  return all;
}
module.exports = {
  platform: "\u7F51\u6613\u4E91\u97F3\u4E50",
  version: "1.3.0",
  srcUrl: "https://droidzf.github.io/musicfree/netease.js",
  author: "zero",
  description: "\u72EC\u7ACB\u7F51\u6613\u4E91\u97F3\u4E50\u63D2\u4EF6\uFF1A\u641C\u7D22\u3001\u64AD\u653E\u3001\u6B4C\u8BCD\u3001\u699C\u5355\u3001\u63A8\u8350\u6B4C\u5355\u3001\u5B8C\u6574\u6B4C\u5355\u8BE6\u60C5\u548C\u8BC4\u8BBA\u3002",
  cacheControl: "no-store",
  supportedSearchType: ["music"],
  userVariables: [
    {
      key: "neteaseEapiKey",
      name: "\u7F51\u6613\u4E91 EAPI AES Key",
      hint: "\u4EC5\u7528\u4E8E\u641C\u7D22\u7B7E\u540D\uFF1B\u8BF7\u81EA\u884C\u586B\u5199\uFF0C\u63D2\u4EF6\u4E0D\u4F1A\u5185\u7F6E APK \u4E2D\u63D0\u53D6\u7684\u5BC6\u94A5\u3002"
    }
  ],
  hints: { importMusicSheet: ["\u652F\u6301\u7F51\u6613\u4E91\u6B4C\u5355\u94FE\u63A5\u6216\u7EAF\u6570\u5B57\u6B4C\u5355 ID\u3002"] },
  search,
  getMediaSource: function(musicItem, quality) {
    return resolveMedia("wy", musicItem, quality);
  },
  getLyric,
  getMusicInfo,
  getTopLists,
  getTopListDetail: function(topListItem, page) {
    return playlistPage(topListItem, page, "topListItem");
  },
  getRecommendSheetTags,
  getRecommendSheetsByTag,
  getMusicSheetInfo: function(sheetItem, page) {
    return playlistPage(sheetItem, page, "sheetItem");
  },
  importMusicSheet,
  getMusicComments: function(musicItem, page) {
    return getComments("wy", musicItem, page);
  }
};
