// Generated by scripts/build.js. Import this file directly into MusicFree.
var __getOwnPropNames = Object.getOwnPropertyNames;
var __commonJS = (cb, mod) => function __require() {
  return mod || (0, cb[__getOwnPropNames(cb)[0]])((mod = { exports: {} }).exports, mod), mod.exports;
};

// src/shared.js
var require_shared = __commonJS({
  "src/shared.js"(exports2, module2) {
    var axios2 = require("axios");
    var PAGE_SIZE2 = 30;
    var UA2 = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36";
    function text2(value, fallback) {
      if (value === void 0 || value === null || value === "") return fallback || "";
      return String(value);
    }
    function stripHtml2(value) {
      return text2(value).replace(/<[^>]*>/g, "").replace(/&amp;/g, "&").replace(/&lt;/g, "<").replace(/&gt;/g, ">").replace(/&quot;/g, '"').replace(/&#39;/g, "'").trim();
    }
    function parseDuration2(value) {
      if (typeof value === "number") {
        return value > 1e5 ? Math.floor(value / 1e3) : Math.floor(value);
      }
      const raw = text2(value);
      if (/^\d+:\d{1,2}$/.test(raw)) {
        const parts = raw.split(":").map(Number);
        return parts[0] * 60 + parts[1];
      }
      const parsed = Number(raw);
      return Number.isFinite(parsed) ? Math.floor(parsed) : void 0;
    }
    function artistNames2(list, separator) {
      if (!Array.isArray(list)) return text2(list, "\u672A\u77E5\u6B4C\u624B");
      return list.map(function(artist) {
        return text2(artist && (artist.name || artist.title || artist.author_name));
      }).filter(Boolean).join(separator || "\u3001");
    }
    function formatLrcTime(seconds) {
      const value = Number(seconds) || 0;
      const minutes = Math.floor(value / 60);
      const rest = (value - minutes * 60).toFixed(2).padStart(5, "0");
      return "[" + String(minutes).padStart(2, "0") + ":" + rest + "]";
    }
    function decodeBase642(value) {
      if (!value) return "";
      try {
        return Buffer.from(value, "base64").toString("utf8");
      } catch (error) {
        return text2(value);
      }
    }
    function userVariables() {
      try {
        return env.getUserVariables() || {};
      } catch (error) {
        return {};
      }
    }
    function qualityLevel(quality) {
      return {
        low: "standard",
        standard: "standard",
        high: "exhigh",
        super: "lossless"
      }[quality] || "standard";
    }
    async function resolveMedia2(source, musicItem, quality) {
      const rid = text2(musicItem.sourceRid || musicItem.rid || musicItem.id);
      const response = await axios2.post(
        "https://musicserver.haitangw.cc/v1/music/resolve-url",
        { source, rid, level: qualityLevel(quality) },
        {
          headers: { "Content-Type": "application/json", Accept: "application/json" },
          timeout: 9e3
        }
      );
      const data = response.data && response.data.data;
      if (!data || !data.url) throw new Error("\u64AD\u653E\u5730\u5740\u89E3\u6790\u5931\u8D25");
      return { url: data.url, headers: data.playbackHeaders || data.headers || void 0 };
    }
    function normalizeComment(item) {
      const rawTime = Number(item.time);
      return {
        id: text2(item.id),
        nickName: text2(item.userName, "\u533F\u540D\u7528\u6237"),
        comment: text2(item.text),
        avatar: text2(item.avatar),
        like: Number(item.likedCount) || 0,
        createAt: Number.isFinite(rawTime) ? rawTime < 1e11 ? rawTime * 1e3 : rawTime : void 0,
        location: text2(item.location),
        replies: Array.isArray(item.reply) ? item.reply.map(function(reply) {
          const normalized = normalizeComment(reply);
          delete normalized.replies;
          return normalized;
        }) : []
      };
    }
    async function getComments2(source, musicItem, page) {
      const currentPage = Math.max(1, Number(page) || 1);
      const rid = text2(musicItem.sourceRid || musicItem.rid || musicItem.id);
      const response = await axios2.get(
        "https://music.haitangw.cc/pinglun/" + source + "pl.php",
        {
          params: { songmid: rid, type: "hot", page: currentPage, limit: 20 },
          headers: { "User-Agent": UA2 },
          timeout: 8e3
        }
      );
      const root = response.data || {};
      if (Number(root.code) !== 200) throw new Error(root.message || "\u8BC4\u8BBA\u52A0\u8F7D\u5931\u8D25");
      const data = root.data || {};
      const comments = Array.isArray(data.comments) ? data.comments : [];
      return {
        isEnd: currentPage >= Number(data.maxPage || 1) || comments.length < 20,
        data: comments.map(normalizeComment)
      };
    }
    function extractNumericId2(value) {
      const matches = text2(value).match(/\d+/g);
      if (!matches || !matches.length) throw new Error("\u65E0\u6CD5\u8BC6\u522B ID");
      return matches[matches.length - 1];
    }
    function createTopListGroups2(platformKey, groups) {
      return groups.map(function(group) {
        return {
          title: group.title,
          data: group.data.map(function(item) {
            return {
              id: text2(item[0]),
              bangId: text2(item[0]),
              title: item[1],
              description: item[2],
              artwork: "https://droidzf.github.io/musicfree/covers/" + platformKey + "-" + text2(item[0]) + ".png"
            };
          })
        };
      });
    }
    module2.exports = {
      axios: axios2,
      PAGE_SIZE: PAGE_SIZE2,
      UA: UA2,
      text: text2,
      stripHtml: stripHtml2,
      parseDuration: parseDuration2,
      artistNames: artistNames2,
      formatLrcTime,
      decodeBase64: decodeBase642,
      userVariables,
      resolveMedia: resolveMedia2,
      getComments: getComments2,
      extractNumericId: extractNumericId2,
      createTopListGroups: createTopListGroups2
    };
  }
});

// src/qq.js
var {
  axios,
  PAGE_SIZE,
  UA,
  text,
  stripHtml,
  parseDuration,
  artistNames,
  decodeBase64,
  resolveMedia,
  getComments,
  extractNumericId,
  createTopListGroups
} = require_shared();
var TOP_LIST_GROUPS = [
  {
    title: "\u5DC5\u5CF0\u699C",
    data: [
      ["4", "\u6D41\u884C\u6307\u6570\u699C", "\u6309\u6B4C\u66F2\u5728 QQ \u97F3\u4E50\u4E2D\u7684\u6D41\u884C\u8D8B\u52BF\u6574\u7406\u3002"],
      ["26", "\u70ED\u6B4C\u699C", "\u5448\u73B0 QQ \u97F3\u4E50\u5F53\u524D\u7EFC\u5408\u70ED\u5EA6\u8F83\u9AD8\u7684\u6B4C\u66F2\u3002"],
      ["27", "\u65B0\u6B4C\u699C", "\u6536\u5F55\u8FD1\u671F\u53D1\u5E03\u5E76\u53D7\u5230\u5173\u6CE8\u7684\u65B0\u6B4C\u3002"],
      ["62", "\u98D9\u5347\u699C", "\u805A\u5408\u8FD1\u671F\u70ED\u5EA6\u5FEB\u901F\u4E0A\u5347\u7684\u6B4C\u66F2\u3002"]
    ]
  },
  {
    title: "\u5730\u533A\u699C",
    data: [
      ["5", "\u5185\u5730\u699C", "\u805A\u5408\u4E2D\u56FD\u5185\u5730\u70ED\u95E8\u6B4C\u66F2\u3002"],
      ["59", "\u9999\u6E2F\u5730\u533A\u699C", "\u805A\u5408\u4E2D\u56FD\u9999\u6E2F\u5730\u533A\u70ED\u95E8\u6B4C\u66F2\u3002"],
      ["61", "\u53F0\u6E7E\u5730\u533A\u699C", "\u805A\u5408\u4E2D\u56FD\u53F0\u6E7E\u5730\u533A\u70ED\u95E8\u6B4C\u66F2\u3002"],
      ["3", "\u6B27\u7F8E\u699C", "\u805A\u5408\u6B27\u7F8E\u5730\u533A\u70ED\u95E8\u6B4C\u66F2\u3002"],
      ["16", "\u97E9\u56FD\u699C", "\u805A\u5408\u97E9\u56FD\u70ED\u95E8\u6B4C\u66F2\u3002"],
      ["17", "\u65E5\u672C\u699C", "\u805A\u5408\u65E5\u672C\u70ED\u95E8\u6B4C\u66F2\u3002"]
    ]
  },
  {
    title: "\u7C7B\u578B\u699C",
    data: [
      ["58", "\u8BF4\u5531\u699C", "\u805A\u5408\u70ED\u95E8\u8BF4\u5531\u4F5C\u54C1\u3002"],
      ["57", "\u559C\u529B\u7535\u97F3\u699C", "\u805A\u5408\u70ED\u95E8\u7535\u5B50\u97F3\u4E50\u4E0E\u821E\u66F2\u4F5C\u54C1\u3002"],
      ["28", "\u7F51\u7EDC\u6B4C\u66F2\u699C", "\u805A\u5408\u8FD1\u671F\u7F51\u7EDC\u70ED\u95E8\u6B4C\u66F2\u3002"],
      ["29", "\u5F71\u89C6\u91D1\u66F2\u699C", "\u805A\u5408\u5F71\u89C6\u5267\u4E0E\u7EFC\u827A\u539F\u58F0\u91D1\u66F2\u3002"],
      ["36", "K\u6B4C\u91D1\u66F2\u699C", "\u805A\u5408\u7528\u6237\u559C\u7231\u7684 K \u6B4C\u70ED\u95E8\u66F2\u76EE\u3002"],
      ["63", "DJ\u821E\u66F2\u699C", "\u805A\u5408\u70ED\u95E8 DJ \u4E0E\u821E\u66F2\u4F5C\u54C1\u3002"],
      ["64", "\u7EFC\u827A\u65B0\u6B4C\u699C", "\u6536\u5F55\u8FD1\u671F\u7EFC\u827A\u8282\u76EE\u70ED\u95E8\u65B0\u6B4C\u3002"],
      ["65", "\u56FD\u98CE\u70ED\u6B4C\u699C", "\u805A\u5408\u70ED\u95E8\u56FD\u98CE\u97F3\u4E50\u4F5C\u54C1\u3002"],
      ["72", "\u52A8\u6F2B\u97F3\u4E50\u699C", "\u805A\u5408\u70ED\u95E8\u52A8\u6F2B\u4E0E\u4E8C\u6B21\u5143\u97F3\u4E50\u3002"]
    ]
  },
  {
    title: "\u7279\u8272\u699C",
    data: [
      ["60", "\u6296\u5FEB\u699C", "\u805A\u5408\u6296\u97F3\u4E0E\u5FEB\u624B\u5E73\u53F0\u8FD1\u671F\u70ED\u95E8\u97F3\u4E50\u3002"],
      ["52", "\u817E\u8BAF\u97F3\u4E50\u4EBA\u539F\u521B\u699C", "\u805A\u5408\u817E\u8BAF\u97F3\u4E50\u4EBA\u539F\u521B\u4F5C\u54C1\u3002"],
      ["67", "\u542C\u6B4C\u8BC6\u66F2\u699C", "\u6309\u542C\u6B4C\u8BC6\u66F2\u70ED\u5EA6\u6574\u7406\u7684\u6B4C\u66F2\u3002"]
    ]
  }
];
var SHEET_TAGS = [
  ["10000000", "\u63A8\u8350"],
  ["167", "\u6D41\u884C"],
  ["185", "\u7F51\u7EDC"],
  ["153", "\u6D41\u884C"],
  ["59", "\u6000\u65E7"],
  ["197", "\u8FD0\u52A8"],
  ["62", "\u5F71\u89C6"],
  ["18", "\u7ECF\u5178"],
  ["16", "\u6447\u6EDA"],
  ["71", "\u60C5\u6B4C"]
];
function qqRequest(moduleName, method, param, requestName) {
  const name = requestName || "req";
  const body = {
    comm: {
      ct: "11",
      cv: "14090508",
      v: "14090508",
      tmeAppID: "qqmusic",
      phonetype: "EBG-AN10",
      os_ver: "12",
      QIMEI36: "0",
      uid: "0",
      sid: "0",
      nettype: "1020",
      modeSwitch: "6",
      teenMode: "0",
      ui_mode: "3"
    }
  };
  body[name] = { module: moduleName, method, param };
  return axios.post("https://u.y.qq.com/cgi-bin/musicu.fcg", body, {
    headers: {
      "Content-Type": "application/json",
      "User-Agent": "QQMusic 14090508(android 12)",
      Referer: "https://y.qq.com/"
    },
    timeout: 9e3
  });
}
function mapMusic(item) {
  const rid = text(item.mid || item.songmid || item.id);
  const album = item.album || {};
  const albumMid = text(album.mid);
  return {
    id: rid,
    title: stripHtml(item.title || item.name),
    artist: artistNames(item.singer),
    album: text(album.name || album.title),
    duration: parseDuration(item.interval),
    artwork: albumMid ? "https://y.gtimg.cn/music/photo_new/T002R500x500M000" + albumMid + ".jpg" : "",
    sourceRid: rid
  };
}
async function search(query, page, type) {
  if (type !== "music") return { isEnd: true, data: [] };
  const currentPage = Math.max(1, Number(page) || 1);
  const response = await qqRequest("music.search.SearchCgiService", "DoSearchForQQMusicMobile", {
    remoteplace: "txt.mqq.all",
    search_type: 0,
    query,
    page_num: currentPage,
    num_per_page: PAGE_SIZE,
    highlight: 0,
    nqc_flag: 0,
    multi_zhida: 0,
    cat: 2,
    grp: 1,
    sin: currentPage * PAGE_SIZE,
    sem: 0
  });
  const req = response.data && response.data.req || {};
  const body = req.data && (req.data.body || req.data) || {};
  const song = body.song || body;
  const list = song.list || body.item_song || body.list || [];
  return { isEnd: list.length < PAGE_SIZE, data: list.map(mapMusic) };
}
async function getLyric(musicItem) {
  const rid = text(musicItem.sourceRid || musicItem.id);
  const response = await qqRequest(
    "music.musichallSong.PlayLyricInfo",
    "GetPlayLyricInfo",
    {
      format: "json",
      crypt: 0,
      ct: 11,
      interval: 0,
      lrc_t: 0,
      trans: 1,
      trans_t: 0,
      type: -1,
      songID: 0,
      songMID: rid
    }
  );
  const data = response.data && response.data.req && response.data.req.data;
  return {
    rawLrc: decodeBase64(data && (data.lyric || data.lyricBase64)),
    translation: decodeBase64(data && (data.trans || data.transBase64))
  };
}
async function getMusicInfo(musicItem) {
  const rid = text(musicItem.sourceRid || musicItem.id);
  const response = await qqRequest(
    "music.trackInfo.UniformRuleCtrl",
    "CgiGetTrackInfo",
    { mids: [rid], types: [0] }
  );
  const tracks = response.data && response.data.req && response.data.req.data && response.data.req.data.tracks;
  return tracks && tracks[0] ? mapMusic(tracks[0]) : {};
}
async function getPeriod(topId) {
  const response = await axios.get("https://c.y.qq.com/node/pc/wk_v15/top.html", {
    headers: { "User-Agent": UA, Referer: "https://y.qq.com/" },
    timeout: 8e3
  });
  const expression = new RegExp(
    'data-listname="[^"]+" data-tid="[^"]*/' + topId + '" data-date="([^"]+)"'
  );
  const match = text(response.data).match(expression);
  if (match) return match[1];
  const date = new Date(Date.now() - 864e5);
  return date.toISOString().split("T")[0];
}
async function getTopListDetail(topListItem, page) {
  const currentPage = Math.max(1, Number(page) || 1);
  if (currentPage > 1) return { isEnd: true, musicList: [] };
  const topId = text(topListItem.bangId || topListItem.id);
  const period = await getPeriod(topId);
  const response = await qqRequest(
    "musicToplist.ToplistInfoServer",
    "GetDetail",
    { topid: Number(topId), num: 100, period },
    "toplist"
  );
  const data = response.data && response.data.toplist && response.data.toplist.data;
  return {
    isEnd: true,
    musicList: (data && data.songInfoList || []).map(mapMusic),
    topListItem: data ? { title: text(data.title || topListItem.title), artwork: text(data.frontPicUrl || data.headPicUrl) } : void 0
  };
}
async function getRecommendSheetsByTag(tag, page) {
  const currentPage = Math.max(1, Number(page) || 1);
  const tagId = text(tag && tag.id, "10000000");
  const body = { comm: { cv: 1602, ct: 20 } };
  if (tagId === "10000000") {
    body.playlist = {
      module: "playlist.PlayListPlazaServer",
      method: "get_playlist_by_tag",
      param: {
        id: 1e7,
        sin: (currentPage - 1) * 15,
        size: 15,
        order: 5,
        cur_page: currentPage
      }
    };
  } else {
    body.playlist = {
      module: "playlist.PlayListCategoryServer",
      method: "get_category_content",
      param: {
        titleid: Number(tagId),
        caller: "0",
        category_id: Number(tagId),
        size: 15,
        page: currentPage - 1,
        use_page: 1
      }
    };
  }
  const response = await axios.post("https://u.y.qq.com/cgi-bin/musicu.fcg", body, {
    headers: { "Content-Type": "application/json", "User-Agent": UA, Referer: "https://y.qq.com/" },
    timeout: 9e3
  });
  const data = response.data && response.data.playlist && response.data.playlist.data;
  const content = data && data.content;
  const list = tagId === "10000000" ? data && data.v_playlist || [] : content && content.v_item || [];
  return {
    isEnd: tagId === "10000000" ? list.length < 15 : currentPage * 15 >= Number(content && content.total_cnt || 0) || list.length < 15,
    data: list.map(function(item) {
      const basic = item.basic || item;
      const cover = basic.cover || {};
      const creator = basic.creator || basic.creator_info || {};
      return {
        id: text(basic.tid),
        title: text(basic.title),
        artist: text(creator.nick),
        artwork: text(basic.cover_url_big || basic.cover_url_medium || cover.big_url || cover.medium_url),
        description: text(basic.desc || basic.rcmdcontent),
        worksNum: Number(basic.song_cnt) || (Array.isArray(basic.song_ids) ? basic.song_ids.length : void 0),
        playCount: Number(basic.play_cnt || basic.access_num) || void 0
      };
    })
  };
}
async function getMusicSheetInfo(sheetItem, page) {
  const currentPage = Math.max(1, Number(page) || 1);
  if (currentPage > 1) return { isEnd: true, musicList: [] };
  const response = await axios.get("https://c.y.qq.com/v8/fcg-bin/fcg_v8_playlist_cp.fcg", {
    params: { id: sheetItem.id, format: "json", newsong: 1, platform: "jqspaframe.json" },
    headers: { "User-Agent": UA, Referer: "https://y.qq.com/" },
    timeout: 9e3
  });
  const sheet = response.data && response.data.data && response.data.data.cdlist && response.data.data.cdlist[0];
  if (!sheet) throw new Error("QQ \u6B4C\u5355\u8BE6\u60C5\u52A0\u8F7D\u5931\u8D25");
  return {
    isEnd: true,
    musicList: (sheet.songlist || []).map(mapMusic),
    sheetItem: {
      title: text(sheet.dissname || sheetItem.title),
      artwork: text(sheet.logo),
      description: text(sheet.desc),
      worksNum: Number(sheet.songnum) || (sheet.songlist || []).length,
      playCount: Number(sheet.visitnum) || void 0,
      artist: text(sheet.nickname)
    }
  };
}
async function importMusicSheet(urlLike) {
  const id = extractNumericId(urlLike);
  return (await getMusicSheetInfo({ id, title: "\u5BFC\u5165\u6B4C\u5355" }, 1)).musicList;
}
module.exports = {
  platform: "QQ\u97F3\u4E50",
  version: "1.2.0",
  srcUrl: "https://droidzf.github.io/musicfree/qq.js",
  author: "zero",
  description: "\u72EC\u7ACB QQ \u97F3\u4E50\u63D2\u4EF6\uFF1A\u641C\u7D22\u3001\u64AD\u653E\u3001\u6B4C\u8BCD\u300122 \u4E2A\u699C\u5355\u3001\u63A8\u8350\u6B4C\u5355\u3001\u6B4C\u5355\u8BE6\u60C5\u548C\u8BC4\u8BBA\u3002",
  cacheControl: "no-store",
  supportedSearchType: ["music"],
  hints: { importMusicSheet: ["\u652F\u6301 QQ \u97F3\u4E50\u6B4C\u5355\u94FE\u63A5\u6216\u7EAF\u6570\u5B57\u6B4C\u5355 ID\u3002"] },
  search,
  getMediaSource: function(musicItem, quality) {
    return resolveMedia("tx", musicItem, quality);
  },
  getLyric,
  getMusicInfo,
  getTopLists: function() {
    return Promise.resolve(createTopListGroups("qq", TOP_LIST_GROUPS));
  },
  getTopListDetail,
  getRecommendSheetTags: function() {
    return Promise.resolve({
      pinned: [{ id: "10000000", title: "\u63A8\u8350" }],
      data: [{ title: "\u6B4C\u5355\u5206\u7C7B", data: SHEET_TAGS.map(function(item) {
        return { id: item[0], title: item[1] };
      }) }]
    });
  },
  getRecommendSheetsByTag,
  getMusicSheetInfo,
  importMusicSheet,
  getMusicComments: function(musicItem, page) {
    return getComments("tx", musicItem, page);
  }
};
