// Generated by scripts/build.js. Import this file directly into MusicFree.
var __getOwnPropNames = Object.getOwnPropertyNames;
var __commonJS = (cb, mod) => function __require() {
  return mod || (0, cb[__getOwnPropNames(cb)[0]])((mod = { exports: {} }).exports, mod), mod.exports;
};

// src/shared.js
var require_shared = __commonJS({
  "src/shared.js"(exports2, module2) {
    var axios2 = require("axios");
    var PAGE_SIZE2 = 30;
    var UA2 = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36";
    function text2(value, fallback) {
      if (value === void 0 || value === null || value === "") return fallback || "";
      return String(value);
    }
    function stripHtml2(value) {
      return text2(value).replace(/<[^>]*>/g, "").replace(/&amp;/g, "&").replace(/&lt;/g, "<").replace(/&gt;/g, ">").replace(/&quot;/g, '"').replace(/&#39;/g, "'").trim();
    }
    function toHttps2(value, size) {
      return text2(value).replace(/^http:\/\//i, "https://").replace(/\{size\}/g, text2(size, "400"));
    }
    function parseJsonp2(value) {
      const raw = text2(value).trim();
      const start = raw.indexOf("(");
      const end = raw.lastIndexOf(")");
      return JSON.parse(start >= 0 && end > start ? raw.slice(start + 1, end) : raw);
    }
    function parseDuration2(value) {
      if (typeof value === "number") {
        return value > 1e5 ? Math.floor(value / 1e3) : Math.floor(value);
      }
      const raw = text2(value);
      if (/^\d+:\d{1,2}$/.test(raw)) {
        const parts = raw.split(":").map(Number);
        return parts[0] * 60 + parts[1];
      }
      const parsed = Number(raw);
      return Number.isFinite(parsed) ? Math.floor(parsed) : void 0;
    }
    function artistNames2(list, separator) {
      if (!Array.isArray(list)) return text2(list, "\u672A\u77E5\u6B4C\u624B");
      return list.map(function(artist) {
        return text2(artist && (artist.name || artist.title || artist.author_name));
      }).filter(Boolean).join(separator || "\u3001");
    }
    function formatLrcTime(seconds) {
      const value = Number(seconds) || 0;
      const minutes = Math.floor(value / 60);
      const rest = (value - minutes * 60).toFixed(2).padStart(5, "0");
      return "[" + String(minutes).padStart(2, "0") + ":" + rest + "]";
    }
    function decodeBase642(value) {
      if (!value) return "";
      try {
        return Buffer.from(value, "base64").toString("utf8");
      } catch (error) {
        return text2(value);
      }
    }
    function userVariables() {
      try {
        return env.getUserVariables() || {};
      } catch (error) {
        return {};
      }
    }
    function qualityLevel(quality) {
      return {
        low: "standard",
        standard: "standard",
        high: "exhigh",
        super: "lossless"
      }[quality] || "standard";
    }
    async function resolveMedia2(source, musicItem, quality) {
      const rid = text2(musicItem.sourceRid || musicItem.rid || musicItem.id);
      const response = await axios2.post(
        "https://musicserver.haitangw.cc/v1/music/resolve-url",
        { source, rid, level: qualityLevel(quality) },
        {
          headers: { "Content-Type": "application/json", Accept: "application/json" },
          timeout: 9e3
        }
      );
      const data = response.data && response.data.data;
      if (!data || !data.url) throw new Error("\u64AD\u653E\u5730\u5740\u89E3\u6790\u5931\u8D25");
      return { url: data.url, headers: data.playbackHeaders || data.headers || void 0 };
    }
    function normalizeComment(item) {
      const rawTime = Number(item.time);
      return {
        id: text2(item.id),
        nickName: text2(item.userName, "\u533F\u540D\u7528\u6237"),
        comment: text2(item.text),
        avatar: text2(item.avatar),
        like: Number(item.likedCount) || 0,
        createAt: Number.isFinite(rawTime) ? rawTime < 1e11 ? rawTime * 1e3 : rawTime : void 0,
        location: text2(item.location),
        replies: Array.isArray(item.reply) ? item.reply.map(function(reply) {
          const normalized = normalizeComment(reply);
          delete normalized.replies;
          return normalized;
        }) : []
      };
    }
    async function getComments2(source, musicItem, page) {
      const currentPage = Math.max(1, Number(page) || 1);
      const rid = text2(musicItem.sourceRid || musicItem.rid || musicItem.id);
      const response = await axios2.get(
        "https://music.haitangw.cc/pinglun/" + source + "pl.php",
        {
          params: { songmid: rid, type: "hot", page: currentPage, limit: 20 },
          headers: { "User-Agent": UA2 },
          timeout: 8e3
        }
      );
      const root = response.data || {};
      if (Number(root.code) !== 200) throw new Error(root.message || "\u8BC4\u8BBA\u52A0\u8F7D\u5931\u8D25");
      const data = root.data || {};
      const comments = Array.isArray(data.comments) ? data.comments : [];
      return {
        isEnd: currentPage >= Number(data.maxPage || 1) || comments.length < 20,
        data: comments.map(normalizeComment)
      };
    }
    function extractNumericId2(value) {
      const matches = text2(value).match(/\d+/g);
      if (!matches || !matches.length) throw new Error("\u65E0\u6CD5\u8BC6\u522B ID");
      return matches[matches.length - 1];
    }
    module2.exports = {
      axios: axios2,
      PAGE_SIZE: PAGE_SIZE2,
      UA: UA2,
      text: text2,
      stripHtml: stripHtml2,
      toHttps: toHttps2,
      parseJsonp: parseJsonp2,
      parseDuration: parseDuration2,
      artistNames: artistNames2,
      formatLrcTime,
      decodeBase64: decodeBase642,
      userVariables,
      resolveMedia: resolveMedia2,
      getComments: getComments2,
      extractNumericId: extractNumericId2
    };
  }
});

// src/qq.js
var {
  axios,
  PAGE_SIZE,
  UA,
  text,
  stripHtml,
  toHttps,
  parseJsonp,
  parseDuration,
  artistNames,
  decodeBase64,
  resolveMedia,
  getComments,
  extractNumericId
} = require_shared();
function qqRequest(moduleName, method, param, requestName) {
  const name = requestName || "req";
  const body = {
    comm: {
      ct: "11",
      cv: "14090508",
      v: "14090508",
      tmeAppID: "qqmusic",
      phonetype: "EBG-AN10",
      os_ver: "12",
      QIMEI36: "0",
      uid: "0",
      sid: "0",
      nettype: "1020",
      modeSwitch: "6",
      teenMode: "0",
      ui_mode: "3"
    }
  };
  body[name] = { module: moduleName, method, param };
  return axios.post("https://u.y.qq.com/cgi-bin/musicu.fcg", body, {
    headers: {
      "Content-Type": "application/json",
      "User-Agent": "QQMusic 14090508(android 12)",
      Referer: "https://y.qq.com/"
    },
    timeout: 9e3
  });
}
function qqMusicuGet(body) {
  return axios.get("https://u.y.qq.com/cgi-bin/musicu.fcg", {
    params: { _: Date.now(), data: JSON.stringify(body) },
    headers: { Cookie: "uin=", "User-Agent": UA, Referer: "https://y.qq.com/" },
    timeout: 9e3
  });
}
function mapMusic(item) {
  const rid = text(item.mid || item.songmid || item.id);
  const album = item.album || {};
  const albumMid = text(album.mid);
  return {
    id: rid,
    title: stripHtml(item.title || item.name),
    artist: artistNames(item.singer),
    album: text(album.name || album.title),
    duration: parseDuration(item.interval),
    artwork: albumMid ? "https://y.gtimg.cn/music/photo_new/T002R500x500M000" + albumMid + ".jpg" : "",
    sourceRid: rid
  };
}
async function getTopLists() {
  const response = await qqMusicuGet({
    comm: {
      g_tk: 5381,
      uin: 123456,
      format: "json",
      inCharset: "utf-8",
      outCharset: "utf-8",
      notice: 0,
      platform: "h5",
      needNewCode: 1,
      ct: 23,
      cv: 0
    },
    topList: {
      module: "musicToplist.ToplistInfoServer",
      method: "GetAll",
      param: {}
    }
  });
  const groups = response.data && response.data.topList && response.data.topList.data && response.data.topList.data.group;
  return (groups || []).map(function(group) {
    return {
      title: text(group.groupName),
      data: (group.toplist || []).map(function(item) {
        const coverImg = toHttps(
          item.frontPicUrl || item.headPicUrl || item.mbFrontPicUrl || item.musichallPicUrl
        );
        return {
          id: text(item.topId),
          bangId: text(item.topId),
          title: text(item.title || item.musichallTitle),
          description: stripHtml(item.intro || item.updateTips || item.titleDetail),
          coverImg,
          artwork: coverImg,
          period: text(item.period),
          updateTime: text(item.updateTime)
        };
      })
    };
  });
}
async function search(query, page, type) {
  if (type !== "music") return { isEnd: true, data: [] };
  const currentPage = Math.max(1, Number(page) || 1);
  const response = await qqRequest("music.search.SearchCgiService", "DoSearchForQQMusicMobile", {
    remoteplace: "txt.mqq.all",
    search_type: 0,
    query,
    page_num: currentPage,
    num_per_page: PAGE_SIZE,
    highlight: 0,
    nqc_flag: 0,
    multi_zhida: 0,
    cat: 2,
    grp: 1,
    sin: currentPage * PAGE_SIZE,
    sem: 0
  });
  const req = response.data && response.data.req || {};
  const body = req.data && (req.data.body || req.data) || {};
  const song = body.song || body;
  const list = song.list || body.item_song || body.list || [];
  return { isEnd: list.length < PAGE_SIZE, data: list.map(mapMusic) };
}
async function getLyric(musicItem) {
  const rid = text(musicItem.sourceRid || musicItem.id);
  const response = await qqRequest(
    "music.musichallSong.PlayLyricInfo",
    "GetPlayLyricInfo",
    {
      format: "json",
      crypt: 0,
      ct: 11,
      interval: 0,
      lrc_t: 0,
      trans: 1,
      trans_t: 0,
      type: -1,
      songID: 0,
      songMID: rid
    }
  );
  const data = response.data && response.data.req && response.data.req.data;
  return {
    rawLrc: decodeBase64(data && (data.lyric || data.lyricBase64)),
    translation: decodeBase64(data && (data.trans || data.transBase64))
  };
}
async function getMusicInfo(musicItem) {
  const rid = text(musicItem.sourceRid || musicItem.id);
  const response = await qqRequest(
    "music.trackInfo.UniformRuleCtrl",
    "CgiGetTrackInfo",
    { mids: [rid], types: [0] }
  );
  const tracks = response.data && response.data.req && response.data.req.data && response.data.req.data.tracks;
  return tracks && tracks[0] ? mapMusic(tracks[0]) : {};
}
async function getPeriod(topId) {
  const response = await axios.get("https://c.y.qq.com/node/pc/wk_v15/top.html", {
    headers: { "User-Agent": UA, Referer: "https://y.qq.com/" },
    timeout: 8e3
  });
  const expression = new RegExp(
    'data-listname="[^"]+" data-tid="[^"]*/' + topId + '" data-date="([^"]+)"'
  );
  const match = text(response.data).match(expression);
  if (match) return match[1];
  const date = new Date(Date.now() - 864e5);
  return date.toISOString().split("T")[0];
}
async function getTopListDetail(topListItem, page) {
  const currentPage = Math.max(1, Number(page) || 1);
  if (currentPage > 1) return { isEnd: true, musicList: [] };
  const topId = text(topListItem.bangId || topListItem.id);
  const period = text(topListItem.period) || await getPeriod(topId);
  const response = await qqRequest(
    "musicToplist.ToplistInfoServer",
    "GetDetail",
    { topid: Number(topId), num: 100, period },
    "toplist"
  );
  const data = response.data && response.data.toplist && response.data.toplist.data;
  const meta = data && data.data || data;
  return {
    isEnd: true,
    musicList: (data && data.songInfoList || []).map(mapMusic),
    topListItem: data ? (function() {
      const coverImg = text(topListItem.coverImg || topListItem.artwork) || text(meta && (meta.frontPicUrl || meta.headPicUrl));
      return {
        title: text(meta && meta.title || topListItem.title),
        coverImg,
        artwork: coverImg
      };
    })() : void 0
  };
}
async function getRecommendSheetsByTag(tag, page) {
  const currentPage = Math.max(1, Number(page) || 1);
  const pageSize = 20;
  const tagId = text(tag && tag.id, "10000000");
  const response = await axios.get(
    "https://c.y.qq.com/splcloud/fcgi-bin/fcg_get_diss_by_tag.fcg",
    {
      params: {
        inCharset: "utf8",
        outCharset: "utf-8",
        sortId: 5,
        categoryId: tagId,
        sin: pageSize * (currentPage - 1),
        ein: pageSize * currentPage - 1
      },
      headers: { "User-Agent": UA, Referer: "https://y.qq.com/" },
      responseType: "text",
      timeout: 9e3
    }
  );
  const data = parseJsonp(response.data).data || {};
  const list = data.list || [];
  return {
    isEnd: currentPage * pageSize >= Number(data.sum || 0) || list.length < pageSize,
    data: list.map(function(item) {
      return {
        id: text(item.dissid),
        title: text(item.dissname),
        artist: text(item.creator && item.creator.name),
        artwork: toHttps(item.imgurl),
        description: text(item.introduction),
        playCount: Number(item.listennum) || void 0
      };
    })
  };
}
async function getRecommendSheetTags() {
  const response = await axios.get(
    "https://c.y.qq.com/splcloud/fcgi-bin/fcg_get_diss_tag_conf.fcg",
    {
      params: { format: "json", inCharset: "utf8", outCharset: "utf-8" },
      headers: { "User-Agent": UA, Referer: "https://y.qq.com/" },
      timeout: 8e3
    }
  );
  const categories = response.data && response.data.data && response.data.data.categories || [];
  const groups = categories.map(function(group) {
    return {
      title: text(group.categoryGroupName),
      data: (group.items || []).map(function(item) {
        return { id: text(item.categoryId), title: text(item.categoryName) };
      })
    };
  }).filter(function(group) {
    return group.data.length > 0;
  });
  return { pinned: [{ id: "10000000", title: "\u5168\u90E8" }], data: groups };
}
async function getMusicSheetInfo(sheetItem, page) {
  const currentPage = Math.max(1, Number(page) || 1);
  if (currentPage > 1) return { isEnd: true, musicList: [] };
  const response = await axios.get("https://c.y.qq.com/v8/fcg-bin/fcg_v8_playlist_cp.fcg", {
    params: { id: sheetItem.id, format: "json", newsong: 1, platform: "jqspaframe.json" },
    headers: { "User-Agent": UA, Referer: "https://y.qq.com/" },
    timeout: 9e3
  });
  const sheet = response.data && response.data.data && response.data.data.cdlist && response.data.data.cdlist[0];
  if (!sheet) throw new Error("QQ \u6B4C\u5355\u8BE6\u60C5\u52A0\u8F7D\u5931\u8D25");
  return {
    isEnd: true,
    musicList: (sheet.songlist || []).map(mapMusic),
    sheetItem: {
      title: text(sheet.dissname || sheetItem.title),
      artwork: text(sheet.logo),
      description: text(sheet.desc),
      worksNum: Number(sheet.songnum) || (sheet.songlist || []).length,
      playCount: Number(sheet.visitnum) || void 0,
      artist: text(sheet.nickname)
    }
  };
}
async function importMusicSheet(urlLike) {
  const id = extractNumericId(urlLike);
  return (await getMusicSheetInfo({ id, title: "\u5BFC\u5165\u6B4C\u5355" }, 1)).musicList;
}
module.exports = {
  platform: "QQ\u97F3\u4E50",
  version: "1.3.0",
  srcUrl: "https://droidzf.github.io/musicfree/qq.js",
  author: "zero",
  description: "\u72EC\u7ACB QQ \u97F3\u4E50\u63D2\u4EF6\uFF1A\u641C\u7D22\u3001\u64AD\u653E\u3001\u6B4C\u8BCD\u3001\u5B98\u65B9\u52A8\u6001\u699C\u5355\u3001\u63A8\u8350\u6B4C\u5355\u3001\u6B4C\u5355\u8BE6\u60C5\u548C\u8BC4\u8BBA\u3002",
  cacheControl: "no-store",
  supportedSearchType: ["music"],
  hints: { importMusicSheet: ["\u652F\u6301 QQ \u97F3\u4E50\u6B4C\u5355\u94FE\u63A5\u6216\u7EAF\u6570\u5B57\u6B4C\u5355 ID\u3002"] },
  search,
  getMediaSource: function(musicItem, quality) {
    return resolveMedia("tx", musicItem, quality);
  },
  getLyric,
  getMusicInfo,
  getTopLists,
  getTopListDetail,
  getRecommendSheetTags,
  getRecommendSheetsByTag,
  getMusicSheetInfo,
  importMusicSheet,
  getMusicComments: function(musicItem, page) {
    return getComments("tx", musicItem, page);
  }
};
